// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accommodations.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccommodation = `-- name: CreateAccommodation :one
INSERT INTO accommodations (trip_id, name, provider, url, address, latitude, longitude, check_in, check_out, price_note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, trip_id, name, provider, url, address, latitude, longitude, check_in, check_out, price_note, created_at, updated_at, auto, auto_key, dismissed, position, booked
`

type CreateAccommodationParams struct {
	TripID    uuid.UUID   `json:"trip_id"`
	Name      string      `json:"name"`
	Provider  *string     `json:"provider"`
	Url       *string     `json:"url"`
	Address   *string     `json:"address"`
	Latitude  *float64    `json:"latitude"`
	Longitude *float64    `json:"longitude"`
	CheckIn   pgtype.Date `json:"check_in"`
	CheckOut  pgtype.Date `json:"check_out"`
	PriceNote *string     `json:"price_note"`
}

func (q *Queries) CreateAccommodation(ctx context.Context, arg CreateAccommodationParams) (Accommodation, error) {
	row := q.db.QueryRow(ctx, createAccommodation,
		arg.TripID,
		arg.Name,
		arg.Provider,
		arg.Url,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.CheckIn,
		arg.CheckOut,
		arg.PriceNote,
	)
	var i Accommodation
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Name,
		&i.Provider,
		&i.Url,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CheckIn,
		&i.CheckOut,
		&i.PriceNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Auto,
		&i.AutoKey,
		&i.Dismissed,
		&i.Position,
		&i.Booked,
	)
	return i, err
}

const deleteAccommodation = `-- name: DeleteAccommodation :execrows
DELETE FROM accommodations WHERE id = $1 AND trip_id = $2
`

type DeleteAccommodationParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteAccommodation(ctx context.Context, arg DeleteAccommodationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccommodation, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleDraftAccommodations = `-- name: DeleteStaleDraftAccommodations :execrows
DELETE FROM accommodations
WHERE trip_id = $1 AND auto = true AND (auto_key IS NULL OR auto_key <> ALL($2::text[]))
`

type DeleteStaleDraftAccommodationsParams struct {
	TripID uuid.UUID `json:"trip_id"`
	Keys   []string  `json:"keys"`
}

// Prunes drafts (and their tombstones) whose itinerary leg no longer exists;
// never touches confirmed rows.
func (q *Queries) DeleteStaleDraftAccommodations(ctx context.Context, arg DeleteStaleDraftAccommodationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleDraftAccommodations, arg.TripID, arg.Keys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dismissDraftAccommodation = `-- name: DismissDraftAccommodation :execrows
UPDATE accommodations SET dismissed = true WHERE id = $1 AND trip_id = $2 AND auto = true
`

type DismissDraftAccommodationParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DismissDraftAccommodation(ctx context.Context, arg DismissDraftAccommodationParams) (int64, error) {
	result, err := q.db.Exec(ctx, dismissDraftAccommodation, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAccommodationsByTrip = `-- name: ListAccommodationsByTrip :many
SELECT id, trip_id, name, provider, url, address, latitude, longitude, check_in, check_out, price_note, created_at, updated_at, auto, auto_key, dismissed, position, booked FROM accommodations WHERE trip_id = $1 AND NOT dismissed ORDER BY position ASC, check_in ASC NULLS LAST, created_at ASC
`

func (q *Queries) ListAccommodationsByTrip(ctx context.Context, tripID uuid.UUID) ([]Accommodation, error) {
	rows, err := q.db.Query(ctx, listAccommodationsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Accommodation
	for rows.Next() {
		var i Accommodation
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Name,
			&i.Provider,
			&i.Url,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.CheckIn,
			&i.CheckOut,
			&i.PriceNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Auto,
			&i.AutoKey,
			&i.Dismissed,
			&i.Position,
			&i.Booked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfirmedAccommodationsByTrip = `-- name: ListConfirmedAccommodationsByTrip :many
SELECT id, trip_id, name, provider, url, address, latitude, longitude, check_in, check_out, price_note, created_at, updated_at, auto, auto_key, dismissed, position, booked FROM accommodations WHERE trip_id = $1 AND auto = false AND NOT dismissed ORDER BY position ASC, check_in ASC NULLS LAST, created_at ASC
`

// Viewer/share/duplicate surface: drafts (auto=true) are editor-only.
func (q *Queries) ListConfirmedAccommodationsByTrip(ctx context.Context, tripID uuid.UUID) ([]Accommodation, error) {
	rows, err := q.db.Query(ctx, listConfirmedAccommodationsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Accommodation
	for rows.Next() {
		var i Accommodation
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Name,
			&i.Provider,
			&i.Url,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.CheckIn,
			&i.CheckOut,
			&i.PriceNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Auto,
			&i.AutoKey,
			&i.Dismissed,
			&i.Position,
			&i.Booked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteAccommodationFromOption = `-- name: PromoteAccommodationFromOption :one
INSERT INTO accommodations (trip_id, name, provider, url, check_in, check_out,
                            price_note, auto, auto_key, booked, dismissed, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, false, $8, true, false, 9999)
ON CONFLICT (trip_id, auto_key) WHERE auto_key IS NOT NULL DO UPDATE SET
    name       = EXCLUDED.name,
    provider   = EXCLUDED.provider,
    url        = EXCLUDED.url,
    check_in   = EXCLUDED.check_in,
    check_out  = EXCLUDED.check_out,
    price_note = EXCLUDED.price_note,
    auto       = false,
    dismissed  = false,
    booked     = true
RETURNING id, trip_id, name, provider, url, address, latitude, longitude, check_in, check_out, price_note, created_at, updated_at, auto, auto_key, dismissed, position, booked
`

type PromoteAccommodationFromOptionParams struct {
	TripID    uuid.UUID   `json:"trip_id"`
	Name      string      `json:"name"`
	Provider  *string     `json:"provider"`
	Url       *string     `json:"url"`
	CheckIn   pgtype.Date `json:"check_in"`
	CheckOut  pgtype.Date `json:"check_out"`
	PriceNote *string     `json:"price_note"`
	AutoKey   *string     `json:"auto_key"`
}

// Materializes a chosen booking option (00065) as the leg's real stay.
//
// Upsert on (trip_id, auto_key), NOT a plain insert: "Add details…" may already
// have created a confirmed row for this leg, and switching winners must rewrite
// that one row. A second insert would leave the claim-once slot matcher
// (trip_detail_derivation.dart) holding one and shunting the other into "Other
// bookings" — visible, confusing, and the exact clutter the shortlist exists to
// remove. So this deliberately has NO `WHERE accommodations.auto` guard, unlike
// UpsertDraftAccommodation: choosing overwrites a suggested draft, a dismissed
// tombstone, and the previous winner alike. One leg, one stay record.
//
// auto_key is stamped with the todo's STORAGE key and it is load-bearing: the
// matcher tests `autoKey == 'stay:<label>'` FIRST and only then falls back to a
// name/address contains against the city label, which "Loft near Old Town"
// fails. Without the stamp every promoted stay would miss its own leg.
//
// address/latitude/longitude stay out of the SET so a hand-typed location
// survives a winner swap; auto=false keeps the row out of sync ownership.
func (q *Queries) PromoteAccommodationFromOption(ctx context.Context, arg PromoteAccommodationFromOptionParams) (Accommodation, error) {
	row := q.db.QueryRow(ctx, promoteAccommodationFromOption,
		arg.TripID,
		arg.Name,
		arg.Provider,
		arg.Url,
		arg.CheckIn,
		arg.CheckOut,
		arg.PriceNote,
		arg.AutoKey,
	)
	var i Accommodation
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Name,
		&i.Provider,
		&i.Url,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CheckIn,
		&i.CheckOut,
		&i.PriceNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Auto,
		&i.AutoKey,
		&i.Dismissed,
		&i.Position,
		&i.Booked,
	)
	return i, err
}

const setAccommodationPosition = `-- name: SetAccommodationPosition :exec
UPDATE accommodations SET position = $3 WHERE id = $1 AND trip_id = $2
`

type SetAccommodationPositionParams struct {
	ID       uuid.UUID `json:"id"`
	TripID   uuid.UUID `json:"trip_id"`
	Position int32     `json:"position"`
}

func (q *Queries) SetAccommodationPosition(ctx context.Context, arg SetAccommodationPositionParams) error {
	_, err := q.db.Exec(ctx, setAccommodationPosition, arg.ID, arg.TripID, arg.Position)
	return err
}

const shiftAccommodationDates = `-- name: ShiftAccommodationDates :execrows
UPDATE accommodations
SET check_in  = check_in  + $1::int,
    check_out = check_out + $1::int
WHERE trip_id = $2
  AND (check_in IS NOT NULL OR check_out IS NOT NULL)
`

type ShiftAccommodationDatesParams struct {
	Days   int32     `json:"days"`
	TripID uuid.UUID `json:"trip_id"`
}

// Whole-trip date shift (agent set_trip_dates). date + int is civil-date
// arithmetic; NULL dates stay NULL. The WHERE keeps execrows an honest
// count of rows that actually shifted.
func (q *Queries) ShiftAccommodationDates(ctx context.Context, arg ShiftAccommodationDatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, shiftAccommodationDates, arg.Days, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const shiftAccommodationDatesFrom = `-- name: ShiftAccommodationDatesFrom :execrows
UPDATE accommodations
SET check_in  = CASE WHEN check_in  >= $1::date THEN check_in  + $2::int ELSE check_in  END,
    check_out = CASE WHEN check_out >= $1::date THEN check_out + $2::int ELSE check_out END
WHERE trip_id = $3
  AND (check_in >= $1::date OR check_out >= $1::date)
`

type ShiftAccommodationDatesFromParams struct {
	FromDate pgtype.Date `json:"from_date"`
	Days     int32       `json:"days"`
	TripID   uuid.UUID   `json:"trip_id"`
}

// Suffix date shift (agent shift_days_from): ShiftAccommodationDates with a
// date floor, applied PER DATE. A stay's two dates are two independent leg
// boundaries (check-in = arrival, check-out = departure), so a stay that
// straddles the pivot keeps its check-in and rides only its check-out — that
// is exactly how the city before the pivot gains its nights. A raw UPDATE, so
// auto drafts shift without being confirmed (unlike UpdateAccommodation,
// whose auto = false would adopt a suggestion the traveler never chose).
// NULL dates stay NULL and rows with no date on or after the floor are not
// counted.
func (q *Queries) ShiftAccommodationDatesFrom(ctx context.Context, arg ShiftAccommodationDatesFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, shiftAccommodationDatesFrom, arg.FromDate, arg.Days, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAccommodation = `-- name: UpdateAccommodation :one
UPDATE accommodations
SET name       = COALESCE($1, name),
    provider   = COALESCE($2, provider),
    url        = COALESCE($3, url),
    address    = COALESCE($4, address),
    latitude   = CASE WHEN $5::bool THEN NULL
                      ELSE COALESCE($6, latitude) END,
    longitude  = CASE WHEN $5::bool THEN NULL
                      ELSE COALESCE($7, longitude) END,
    check_in   = COALESCE($8, check_in),
    check_out  = COALESCE($9, check_out),
    price_note = COALESCE($10, price_note),
    booked     = COALESCE($11, booked),
    auto       = false
WHERE id = $12 AND trip_id = $13 AND NOT dismissed
RETURNING id, trip_id, name, provider, url, address, latitude, longitude, check_in, check_out, price_note, created_at, updated_at, auto, auto_key, dismissed, position, booked
`

type UpdateAccommodationParams struct {
	Name          *string     `json:"name"`
	Provider      *string     `json:"provider"`
	Url           *string     `json:"url"`
	Address       *string     `json:"address"`
	ClearLocation bool        `json:"clear_location"`
	Latitude      *float64    `json:"latitude"`
	Longitude     *float64    `json:"longitude"`
	CheckIn       pgtype.Date `json:"check_in"`
	CheckOut      pgtype.Date `json:"check_out"`
	PriceNote     *string     `json:"price_note"`
	Booked        *bool       `json:"booked"`
	ID            uuid.UUID   `json:"id"`
	TripID        uuid.UUID   `json:"trip_id"`
}

// Partial update (COALESCE sqlc.narg idiom, see query/trips.sql UpdateTrip).
// Any edit confirms a draft (auto = false), taking it out of sync ownership.
// COALESCE means fields can be overwritten but not cleared back to NULL —
// which is why coordinates need clear_location: detaching a stay's place must
// write NULL, and COALESCE structurally cannot (the trip-description lesson,
// specs/trip-description). One statement stays the one writer.
func (q *Queries) UpdateAccommodation(ctx context.Context, arg UpdateAccommodationParams) (Accommodation, error) {
	row := q.db.QueryRow(ctx, updateAccommodation,
		arg.Name,
		arg.Provider,
		arg.Url,
		arg.Address,
		arg.ClearLocation,
		arg.Latitude,
		arg.Longitude,
		arg.CheckIn,
		arg.CheckOut,
		arg.PriceNote,
		arg.Booked,
		arg.ID,
		arg.TripID,
	)
	var i Accommodation
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Name,
		&i.Provider,
		&i.Url,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CheckIn,
		&i.CheckOut,
		&i.PriceNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Auto,
		&i.AutoKey,
		&i.Dismissed,
		&i.Position,
		&i.Booked,
	)
	return i, err
}

const upsertDraftAccommodation = `-- name: UpsertDraftAccommodation :execrows
INSERT INTO accommodations (trip_id, name, address, check_in, check_out, auto, auto_key)
VALUES ($1, $2, $3, $4, $5, true, $6)
ON CONFLICT (trip_id, auto_key) WHERE auto_key IS NOT NULL DO UPDATE SET
    name      = EXCLUDED.name,
    address   = EXCLUDED.address,
    check_in  = EXCLUDED.check_in,
    check_out = EXCLUDED.check_out
WHERE accommodations.auto AND NOT accommodations.dismissed
`

type UpsertDraftAccommodationParams struct {
	TripID   uuid.UUID   `json:"trip_id"`
	Name     string      `json:"name"`
	Address  *string     `json:"address"`
	CheckIn  pgtype.Date `json:"check_in"`
	CheckOut pgtype.Date `json:"check_out"`
	AutoKey  *string     `json:"auto_key"`
}

// The WHERE guard leaves confirmed (auto=false) and dismissed rows untouched,
// so this must be :execrows — a skipped conflict returns no row.
func (q *Queries) UpsertDraftAccommodation(ctx context.Context, arg UpsertDraftAccommodationParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertDraftAccommodation,
		arg.TripID,
		arg.Name,
		arg.Address,
		arg.CheckIn,
		arg.CheckOut,
		arg.AutoKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
