// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: booking_todos.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adoptLegacyHomeBookingTodo = `-- name: AdoptLegacyHomeBookingTodo :execrows
UPDATE booking_todos b
SET todo_key = $1::text
WHERE b.trip_id = $2 AND b.todo_key = $3::text
  AND b.auto = true AND b.kind = 'transport'
  AND NOT EXISTS (
        SELECT 1 FROM booking_todos x
        WHERE x.trip_id = b.trip_id AND x.todo_key = $1::text)
`

type AdoptLegacyHomeBookingTodoParams struct {
	NewKey string    `json:"new_key"`
	TripID uuid.UUID `json:"trip_id"`
	OldKey string    `json:"old_key"`
}

// Renames a home leg still stored under its endpoint-labelled key onto the
// canonical @home identity, in place.
//
// Migration 00064 backfills these, so this is the belt to that migration's
// braces: it also catches a row written by an older binary during the deploy
// itself, and it means a failed or skipped backfill degrades to "the next sync
// fixes it" rather than to orphaned rows. Without it a legacy row would simply
// fall outside the posted key set and be pruned — taking its booked flag with
// it, which is the whole bug.
//
// Renames only when nothing already holds the canonical key, so it can never
// violate idx_booking_todos_trip_key; the caller's upsert then writes the
// content either way.
func (q *Queries) AdoptLegacyHomeBookingTodo(ctx context.Context, arg AdoptLegacyHomeBookingTodoParams) (int64, error) {
	result, err := q.db.Exec(ctx, adoptLegacyHomeBookingTodo, arg.NewKey, arg.TripID, arg.OldKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createBookingTodo = `-- name: CreateBookingTodo :one
INSERT INTO booking_todos (trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, position, auto)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, false)
RETURNING id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at, mode, role, origin_label, destination_label, derived_mode
`

type CreateBookingTodoParams struct {
	TripID     uuid.UUID   `json:"trip_id"`
	Kind       string      `json:"kind"`
	TodoKey    string      `json:"todo_key"`
	Title      string      `json:"title"`
	Subtitle   *string     `json:"subtitle"`
	Provider   *string     `json:"provider"`
	SearchUrl  *string     `json:"search_url"`
	DepartDate pgtype.Date `json:"depart_date"`
	ReturnDate pgtype.Date `json:"return_date"`
	Position   int32       `json:"position"`
}

func (q *Queries) CreateBookingTodo(ctx context.Context, arg CreateBookingTodoParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, createBookingTodo,
		arg.TripID,
		arg.Kind,
		arg.TodoKey,
		arg.Title,
		arg.Subtitle,
		arg.Provider,
		arg.SearchUrl,
		arg.DepartDate,
		arg.ReturnDate,
		arg.Position,
	)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Role,
		&i.OriginLabel,
		&i.DestinationLabel,
		&i.DerivedMode,
	)
	return i, err
}

const deleteBookingTodo = `-- name: DeleteBookingTodo :execrows
DELETE FROM booking_todos WHERE id = $1 AND trip_id = $2
`

type DeleteBookingTodoParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteBookingTodo(ctx context.Context, arg DeleteBookingTodoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBookingTodo, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBookingTodoNonAuto = `-- name: DeleteBookingTodoNonAuto :execrows
DELETE FROM booking_todos WHERE id = $1 AND trip_id = $2 AND auto = false
`

type DeleteBookingTodoNonAutoParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteBookingTodoNonAuto(ctx context.Context, arg DeleteBookingTodoNonAutoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBookingTodoNonAuto, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCleanAutoBookingTodoByKey = `-- name: DeleteCleanAutoBookingTodoByKey :execrows
DELETE FROM booking_todos b
WHERE b.trip_id = $1 AND b.todo_key = $2
  AND b.auto = true AND b.booked = false AND b.mode IS NULL
  AND NOT EXISTS (SELECT 1 FROM booking_options o WHERE o.booking_todo_id = b.id)
  AND NOT EXISTS (
        SELECT 1 FROM trip_expenses e
        WHERE e.trip_id = b.trip_id
          AND e.source_kind = 'booking_todo' AND e.source_id = b.id)
`

type DeleteCleanAutoBookingTodoByKeyParams struct {
	TripID  uuid.UUID `json:"trip_id"`
	TodoKey string    `json:"todo_key"`
}

// Clears the way for MigrateBookingTodoLeg: removes the auto row holding the
// target key, but only while it is provably disposable — unbooked, no mode
// choice, no shortlist, no expense link (the same four kinds of traveler
// state DemoteStaleAutoBookingTodos protects). A state-carrying holder
// survives, and MigrateBookingTodoLeg's own NOT EXISTS guard then refuses
// the move: merging two traveler-claimed rows is the traveler's call.
func (q *Queries) DeleteCleanAutoBookingTodoByKey(ctx context.Context, arg DeleteCleanAutoBookingTodoByKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCleanAutoBookingTodoByKey, arg.TripID, arg.TodoKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleAutoBookingTodos = `-- name: DeleteStaleAutoBookingTodos :execrows
DELETE FROM booking_todos
WHERE trip_id = $1 AND auto = true AND todo_key <> ALL($2::text[])
`

type DeleteStaleAutoBookingTodosParams struct {
	TripID uuid.UUID `json:"trip_id"`
	Keys   []string  `json:"keys"`
}

// The rest of the prune: stale rows nobody has touched. Runs AFTER
// DemoteStaleAutoBookingTodos, whose survivors are auto = false by then and so
// fall outside this statement.
func (q *Queries) DeleteStaleAutoBookingTodos(ctx context.Context, arg DeleteStaleAutoBookingTodosParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleAutoBookingTodos, arg.TripID, arg.Keys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const demoteStaleAutoBookingTodos = `-- name: DemoteStaleAutoBookingTodos :execrows
UPDATE booking_todos b
SET auto = false
WHERE b.trip_id = $1 AND b.auto = true AND b.todo_key <> ALL($2::text[])
  AND (b.booked OR b.mode IS NOT NULL
       OR EXISTS (SELECT 1 FROM booking_options o WHERE o.booking_todo_id = b.id)
       OR EXISTS (
        SELECT 1 FROM trip_expenses e
        WHERE e.trip_id = b.trip_id
          AND e.source_kind = 'booking_todo' AND e.source_id = b.id))
`

type DemoteStaleAutoBookingTodosParams struct {
	TripID uuid.UUID `json:"trip_id"`
	Keys   []string  `json:"keys"`
}

// Half of the prune, and it MUST run before DeleteStaleAutoBookingTodos.
//
// A stale auto row that carries traveler state is not garbage — it is a booked
// flight, a per-leg mode override, or the source of a budget expense. Deleting
// it destroys all three silently (the expense survives with a dangling
// source_id, still summed into `spent`, and unbooking can never find it again
// — 00061 has no FK by design). So state-carrying rows are DEMOTED to manual
// instead: auto = false takes them out of the derived set for good, they stop
// being re-derived, and they render in the existing residual "Other bookings"
// list where the traveler and the agent can edit or remove them. Demote rather
// than merely skip: DeleteBookingTodoNonAuto refuses auto rows, so a skipped
// survivor would be an undeletable zombie.
//
// A saved shortlist (00065) is the fourth kind of traveler state, and the most
// expensive to lose: booking_options CASCADEs off this row, so a delete here
// silently destroys hand-collected research. Dropping a city from the itinerary
// must not throw away the three Airbnbs someone compared for it.
func (q *Queries) DemoteStaleAutoBookingTodos(ctx context.Context, arg DemoteStaleAutoBookingTodosParams) (int64, error) {
	result, err := q.db.Exec(ctx, demoteStaleAutoBookingTodos, arg.TripID, arg.Keys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBookingTodo = `-- name: GetBookingTodo :one
SELECT id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at, mode, role, origin_label, destination_label, derived_mode FROM booking_todos WHERE id = $1 AND trip_id = $2
`

type GetBookingTodoParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

// Single leg, scoped to its trip so a foreign id can never be read or attached
// to. Added for the booking-options paths (00065), which must confirm the leg
// a candidate is being hung off actually belongs to this trip.
func (q *Queries) GetBookingTodo(ctx context.Context, arg GetBookingTodoParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, getBookingTodo, arg.ID, arg.TripID)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Role,
		&i.OriginLabel,
		&i.DestinationLabel,
		&i.DerivedMode,
	)
	return i, err
}

const getBookingTodoDeleteState = `-- name: GetBookingTodoDeleteState :one
SELECT b.title, b.booked,
       (SELECT count(*)::int FROM booking_options o WHERE o.booking_todo_id = b.id) AS option_count,
       EXISTS (SELECT 1 FROM trip_expenses e
               WHERE e.trip_id = b.trip_id
                 AND e.source_kind = 'booking_todo' AND e.source_id = b.id) AS has_expense
FROM booking_todos b
WHERE b.id = $1 AND b.trip_id = $2 AND b.auto = false
`

type GetBookingTodoDeleteStateParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

type GetBookingTodoDeleteStateRow struct {
	Title       string `json:"title"`
	Booked      bool   `json:"booked"`
	OptionCount int32  `json:"option_count"`
	HasExpense  bool   `json:"has_expense"`
}

// Pre-delete read for the agent's remove_booking_todo guard — the second delete
// path, the one DemoteStaleAutoBookingTodos' policy does not cover (the demote
// preserves a state-carrying row as auto = false; this statement is what stops
// the agent then hard-deleting that survivor). Same state-carrying predicate as
// the demote MINUS mode: booked, a saved shortlist (booking_options CASCADEs
// off this row), or a linked trip_expenses row (00061's untyped pair — the
// expense survives a delete, dangling and still summed into `spent`). A mode
// override alone is cheap to re-make, so it is deliberately not guarded.
// Scoped auto = false so an auto row reads as "no such row" and the caller
// answers with the same refusal DeleteBookingTodoNonAuto gives today.
func (q *Queries) GetBookingTodoDeleteState(ctx context.Context, arg GetBookingTodoDeleteStateParams) (GetBookingTodoDeleteStateRow, error) {
	row := q.db.QueryRow(ctx, getBookingTodoDeleteState, arg.ID, arg.TripID)
	var i GetBookingTodoDeleteStateRow
	err := row.Scan(
		&i.Title,
		&i.Booked,
		&i.OptionCount,
		&i.HasExpense,
	)
	return i, err
}

const listBookingTodosByTrip = `-- name: ListBookingTodosByTrip :many
SELECT id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at, mode, role, origin_label, destination_label, derived_mode FROM booking_todos WHERE trip_id = $1 ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListBookingTodosByTrip(ctx context.Context, tripID uuid.UUID) ([]BookingTodo, error) {
	rows, err := q.db.Query(ctx, listBookingTodosByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingTodo
	for rows.Next() {
		var i BookingTodo
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Kind,
			&i.TodoKey,
			&i.Title,
			&i.Subtitle,
			&i.Provider,
			&i.SearchUrl,
			&i.DepartDate,
			&i.ReturnDate,
			&i.Booked,
			&i.Auto,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Mode,
			&i.Role,
			&i.OriginLabel,
			&i.DestinationLabel,
			&i.DerivedMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeBookingTodos = `-- name: ListHomeBookingTodos :many
SELECT id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at, mode, role, origin_label, destination_label, derived_mode FROM booking_todos
WHERE trip_id = $1 AND auto = true AND role IN ('home_outbound', 'home_return')
ORDER BY position ASC, created_at ASC
`

// The trip's two journey-endpoint rows, in checklist order. Used when the
// trip's endpoints change so their labels can be refreshed immediately rather
// than at the next client sync — a tool that reports "the checklist now reads
// ALB → Amsterdam" has to have made that true before it says so.
func (q *Queries) ListHomeBookingTodos(ctx context.Context, tripID uuid.UUID) ([]BookingTodo, error) {
	rows, err := q.db.Query(ctx, listHomeBookingTodos, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookingTodo
	for rows.Next() {
		var i BookingTodo
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Kind,
			&i.TodoKey,
			&i.Title,
			&i.Subtitle,
			&i.Provider,
			&i.SearchUrl,
			&i.DepartDate,
			&i.ReturnDate,
			&i.Booked,
			&i.Auto,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Mode,
			&i.Role,
			&i.OriginLabel,
			&i.DestinationLabel,
			&i.DerivedMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const migrateBookingTodoLeg = `-- name: MigrateBookingTodoLeg :one
UPDATE booking_todos b
SET todo_key = $1,
    origin_label = $2,
    destination_label = $3,
    title = $4,
    depart_date = $5,
    search_url = $6,
    provider = $7,
    derived_mode = $8
WHERE b.id = $9 AND b.trip_id = $10
  AND b.auto = false AND b.kind = 'transport'
  AND NOT EXISTS (
        SELECT 1 FROM booking_todos x
        WHERE x.trip_id = b.trip_id AND x.todo_key = $1 AND x.id <> b.id)
RETURNING id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at, mode, role, origin_label, destination_label, derived_mode
`

type MigrateBookingTodoLegParams struct {
	TodoKey          string      `json:"todo_key"`
	OriginLabel      *string     `json:"origin_label"`
	DestinationLabel *string     `json:"destination_label"`
	Title            string      `json:"title"`
	DepartDate       pgtype.Date `json:"depart_date"`
	SearchUrl        *string     `json:"search_url"`
	Provider         *string     `json:"provider"`
	DerivedMode      *string     `json:"derived_mode"`
	ID               uuid.UUID   `json:"id"`
	TripID           uuid.UUID   `json:"trip_id"`
}

// Re-keys a MANUAL (auto = false) transport todo onto the leg that replaced
// it after the route changed — todo_key, labels, title, depart_date, provider,
// search_url and derived_mode recomputed for the new leg — preserving the row
// id, so booked, mode, position, the booking_options shortlist (CASCADE off
// this id) and any trip_expenses.source_id link all ride along. Create-new +
// delete-old would silently destroy the shortlist and dangle the money — the
// exact losses DemoteStaleAutoBookingTodos's docstring enumerates — and
// UpdateBookingTodo cannot do this (auto = false only, no key/label columns);
// a migration is a different act with its own guard.
//
// The statement's own guards: the row must be a manual transport row of this
// trip, and the target key must be FREE. The handler deletes a clean auto
// holder first (DeleteCleanAutoBookingTodoByKey), so a holder that survives
// to this statement is by definition state-carrying and the update refuses.
// The "refuse when the todo's pair is still adjacent" guard lives in Go
// (booking_todo_migrate.go): adjacency is a fact about the itinerary, which
// SQL cannot see.
func (q *Queries) MigrateBookingTodoLeg(ctx context.Context, arg MigrateBookingTodoLegParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, migrateBookingTodoLeg,
		arg.TodoKey,
		arg.OriginLabel,
		arg.DestinationLabel,
		arg.Title,
		arg.DepartDate,
		arg.SearchUrl,
		arg.Provider,
		arg.DerivedMode,
		arg.ID,
		arg.TripID,
	)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Role,
		&i.OriginLabel,
		&i.DestinationLabel,
		&i.DerivedMode,
	)
	return i, err
}

const relabelHomeBookingTodo = `-- name: RelabelHomeBookingTodo :one
UPDATE booking_todos
SET origin_label = $1,
    destination_label = $2,
    title = $3,
    search_url = $4,
    provider = $5
WHERE id = $6 AND trip_id = $7
RETURNING id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at, mode, role, origin_label, destination_label, derived_mode
`

type RelabelHomeBookingTodoParams struct {
	OriginLabel      *string   `json:"origin_label"`
	DestinationLabel *string   `json:"destination_label"`
	Title            string    `json:"title"`
	SearchUrl        *string   `json:"search_url"`
	Provider         *string   `json:"provider"`
	ID               uuid.UUID `json:"id"`
	TripID           uuid.UUID `json:"trip_id"`
}

// Repoints ONE journey-endpoint row at a new airport. Content only: the row
// keeps its id, so booked, mode, position and any trip_expenses row linked by
// source_id ride along untouched — which is the entire reason the key stopped
// containing the airport (00064). todo_key is deliberately absent: the @home
// identity does not move when the label does.
func (q *Queries) RelabelHomeBookingTodo(ctx context.Context, arg RelabelHomeBookingTodoParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, relabelHomeBookingTodo,
		arg.OriginLabel,
		arg.DestinationLabel,
		arg.Title,
		arg.SearchUrl,
		arg.Provider,
		arg.ID,
		arg.TripID,
	)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Role,
		&i.OriginLabel,
		&i.DestinationLabel,
		&i.DerivedMode,
	)
	return i, err
}

const setBookingTodoBooked = `-- name: SetBookingTodoBooked :one
UPDATE booking_todos SET booked = $3 WHERE id = $1 AND trip_id = $2 RETURNING id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at, mode, role, origin_label, destination_label, derived_mode
`

type SetBookingTodoBookedParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
	Booked bool      `json:"booked"`
}

func (q *Queries) SetBookingTodoBooked(ctx context.Context, arg SetBookingTodoBookedParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, setBookingTodoBooked, arg.ID, arg.TripID, arg.Booked)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Role,
		&i.OriginLabel,
		&i.DestinationLabel,
		&i.DerivedMode,
	)
	return i, err
}

const setBookingTodoMode = `-- name: SetBookingTodoMode :one
UPDATE booking_todos
SET mode = $3, provider = $4, search_url = $5
WHERE id = $1 AND trip_id = $2 AND kind = 'transport'
RETURNING id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at, mode, role, origin_label, destination_label, derived_mode
`

type SetBookingTodoModeParams struct {
	ID        uuid.UUID `json:"id"`
	TripID    uuid.UUID `json:"trip_id"`
	Mode      *string   `json:"mode"`
	Provider  *string   `json:"provider"`
	SearchUrl *string   `json:"search_url"`
}

// Per-leg transport-mode override. Works on auto rows (like SetBookingTodoBooked
// and unlike UpdateBookingTodo) and never touches booked/auto; provider and
// search_url are rebuilt by the handler to match the new mode. transport-only
// by design — a stay/other row 404s.
func (q *Queries) SetBookingTodoMode(ctx context.Context, arg SetBookingTodoModeParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, setBookingTodoMode,
		arg.ID,
		arg.TripID,
		arg.Mode,
		arg.Provider,
		arg.SearchUrl,
	)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Role,
		&i.OriginLabel,
		&i.DestinationLabel,
		&i.DerivedMode,
	)
	return i, err
}

const setBookingTodoPositionsBatch = `-- name: SetBookingTodoPositionsBatch :exec
UPDATE booking_todos b
SET position = u.pos
FROM (
    SELECT unnest($2::uuid[])      AS id,
           unnest($3::int[]) AS pos
) AS u
WHERE b.id = u.id AND b.trip_id = $1::uuid
`

type SetBookingTodoPositionsBatchParams struct {
	TripID    uuid.UUID   `json:"trip_id"`
	Ids       []uuid.UUID `json:"ids"`
	Positions []int32     `json:"positions"`
}

// One round trip for the whole reorder. ids and positions are parallel
// arrays; every row is scoped to trip_id so a foreign id can never move
// another trip's row.
func (q *Queries) SetBookingTodoPositionsBatch(ctx context.Context, arg SetBookingTodoPositionsBatchParams) error {
	_, err := q.db.Exec(ctx, setBookingTodoPositionsBatch, arg.TripID, arg.Ids, arg.Positions)
	return err
}

const shiftBookingTodoDates = `-- name: ShiftBookingTodoDates :execrows
UPDATE booking_todos
SET depart_date = depart_date + $1::int,
    return_date = return_date + $1::int
WHERE trip_id = $2
  AND (depart_date IS NOT NULL OR return_date IS NOT NULL)
`

type ShiftBookingTodoDatesParams struct {
	Days   int32     `json:"days"`
	TripID uuid.UUID `json:"trip_id"`
}

// Whole-trip date shift (agent set_trip_dates); see ShiftAccommodationDates.
func (q *Queries) ShiftBookingTodoDates(ctx context.Context, arg ShiftBookingTodoDatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, shiftBookingTodoDates, arg.Days, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const shiftBookingTodoDatesFrom = `-- name: ShiftBookingTodoDatesFrom :execrows
UPDATE booking_todos
SET depart_date = CASE WHEN depart_date >= $1::date THEN depart_date + $2::int ELSE depart_date END,
    return_date = CASE WHEN return_date >= $1::date THEN return_date + $2::int ELSE return_date END
WHERE trip_id = $3
  AND (depart_date >= $1::date OR return_date >= $1::date)
`

type ShiftBookingTodoDatesFromParams struct {
	FromDate pgtype.Date `json:"from_date"`
	Days     int32       `json:"days"`
	TripID   uuid.UUID   `json:"trip_id"`
}

// Suffix date shift (agent shift_days_from): ShiftBookingTodoDates with a
// date floor, applied PER DATE like ShiftAccommodationDatesFrom — a row's two
// dates can be two separate bookings (a round-trip flight todo departs before
// the pivot and returns after it; only the return moves). A raw UPDATE works
// on auto rows too, which UpdateBookingTodo refuses; the next client sync
// re-derives them either way, this just keeps them true in the meantime.
// NULL dates stay NULL and rows with no date on or after the floor are not
// counted.
func (q *Queries) ShiftBookingTodoDatesFrom(ctx context.Context, arg ShiftBookingTodoDatesFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, shiftBookingTodoDatesFrom, arg.FromDate, arg.Days, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBookingTodo = `-- name: UpdateBookingTodo :one
UPDATE booking_todos
SET kind        = COALESCE($1, kind),
    title       = COALESCE($2, title),
    subtitle    = COALESCE($3, subtitle),
    depart_date = COALESCE($4, depart_date),
    return_date = COALESCE($5, return_date),
    search_url  = COALESCE($6, search_url),
    provider    = COALESCE($7, provider),
    booked      = COALESCE($8, booked)
WHERE id = $9 AND trip_id = $10 AND auto = false
RETURNING id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at, mode, role, origin_label, destination_label, derived_mode
`

type UpdateBookingTodoParams struct {
	Kind       *string     `json:"kind"`
	Title      *string     `json:"title"`
	Subtitle   *string     `json:"subtitle"`
	DepartDate pgtype.Date `json:"depart_date"`
	ReturnDate pgtype.Date `json:"return_date"`
	SearchUrl  *string     `json:"search_url"`
	Provider   *string     `json:"provider"`
	Booked     *bool       `json:"booked"`
	ID         uuid.UUID   `json:"id"`
	TripID     uuid.UUID   `json:"trip_id"`
}

// Partial update (COALESCE sqlc.narg idiom, see query/trips.sql UpdateTrip).
// auto = false only: auto rows are owned by the client's itinerary sync and
// would be overwritten on the next sync. COALESCE means fields can be
// overwritten but not cleared back to NULL.
func (q *Queries) UpdateBookingTodo(ctx context.Context, arg UpdateBookingTodoParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, updateBookingTodo,
		arg.Kind,
		arg.Title,
		arg.Subtitle,
		arg.DepartDate,
		arg.ReturnDate,
		arg.SearchUrl,
		arg.Provider,
		arg.Booked,
		arg.ID,
		arg.TripID,
	)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Role,
		&i.OriginLabel,
		&i.DestinationLabel,
		&i.DerivedMode,
	)
	return i, err
}

const upsertBookingTodo = `-- name: UpsertBookingTodo :one
INSERT INTO booking_todos (trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, position, auto, role, origin_label, destination_label, derived_mode)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, true, $11, $12, $13, $14)
ON CONFLICT (trip_id, todo_key) DO UPDATE SET
    kind = EXCLUDED.kind,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    provider = EXCLUDED.provider,
    search_url = EXCLUDED.search_url,
    depart_date = EXCLUDED.depart_date,
    return_date = EXCLUDED.return_date,
    position = EXCLUDED.position,
    role = EXCLUDED.role,
    origin_label = EXCLUDED.origin_label,
    destination_label = EXCLUDED.destination_label,
    derived_mode = EXCLUDED.derived_mode
RETURNING id, trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, booked, auto, position, created_at, updated_at, mode, role, origin_label, destination_label, derived_mode
`

type UpsertBookingTodoParams struct {
	TripID           uuid.UUID   `json:"trip_id"`
	Kind             string      `json:"kind"`
	TodoKey          string      `json:"todo_key"`
	Title            string      `json:"title"`
	Subtitle         *string     `json:"subtitle"`
	Provider         *string     `json:"provider"`
	SearchUrl        *string     `json:"search_url"`
	DepartDate       pgtype.Date `json:"depart_date"`
	ReturnDate       pgtype.Date `json:"return_date"`
	Position         int32       `json:"position"`
	Role             *string     `json:"role"`
	OriginLabel      *string     `json:"origin_label"`
	DestinationLabel *string     `json:"destination_label"`
	DerivedMode      *string     `json:"derived_mode"`
}

// KEPT deliberately though no handler calls it directly: it is the semantic
// reference for UpsertBookingTodosBatch's column list / ON CONFLICT set, and
// its generated Params struct is the row type the batch path builds
// (booking_todo_handler.go). Delete only together with a handler refactor.
//
// role/origin_label/destination_label (00064) are CONTENT, like title: they
// ride the DO UPDATE set so a re-sync refreshes them. So does derived_mode
// (00068) — what the server worked out for the leg, refreshed alongside the
// provider and search_url it decides. What must never join the set is
// booked/auto/mode — that exclusion is the whole preservation contract, and
// it is what lets a changed departure airport rewrite a home leg in place.
func (q *Queries) UpsertBookingTodo(ctx context.Context, arg UpsertBookingTodoParams) (BookingTodo, error) {
	row := q.db.QueryRow(ctx, upsertBookingTodo,
		arg.TripID,
		arg.Kind,
		arg.TodoKey,
		arg.Title,
		arg.Subtitle,
		arg.Provider,
		arg.SearchUrl,
		arg.DepartDate,
		arg.ReturnDate,
		arg.Position,
		arg.Role,
		arg.OriginLabel,
		arg.DestinationLabel,
		arg.DerivedMode,
	)
	var i BookingTodo
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Kind,
		&i.TodoKey,
		&i.Title,
		&i.Subtitle,
		&i.Provider,
		&i.SearchUrl,
		&i.DepartDate,
		&i.ReturnDate,
		&i.Booked,
		&i.Auto,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Role,
		&i.OriginLabel,
		&i.DestinationLabel,
		&i.DerivedMode,
	)
	return i, err
}

const upsertBookingTodosBatch = `-- name: UpsertBookingTodosBatch :exec
INSERT INTO booking_todos (trip_id, kind, todo_key, title, subtitle, provider, search_url, depart_date, return_date, position, auto, role, origin_label, destination_label, derived_mode)
SELECT $1::uuid, u.kind, u.todo_key, u.title,
       CASE WHEN u.subtitle_null THEN NULL ELSE u.subtitle END,
       CASE WHEN u.provider_null THEN NULL ELSE u.provider END,
       CASE WHEN u.search_url_null THEN NULL ELSE u.search_url END,
       u.depart_date, u.return_date, u.position, true,
       u.role,
       -- A label has no meaningful empty value, so NULLIF carries the "this
       -- row has no origin" case (every stay row) without a third null mask.
       -- Same for derived_mode: a stay leg has none.
       NULLIF(u.origin_label, ''), NULLIF(u.destination_label, ''),
       NULLIF(u.derived_mode, '')
FROM (
    SELECT unnest($2::text[])            AS kind,
           unnest($3::text[])        AS todo_key,
           unnest($4::text[])           AS title,
           unnest($5::text[])        AS subtitle,
           unnest($6::bool[])   AS subtitle_null,
           unnest($7::text[])        AS provider,
           unnest($8::bool[])   AS provider_null,
           unnest($9::text[])      AS search_url,
           unnest($10::bool[]) AS search_url_null,
           unnest($11::date[])     AS depart_date,
           unnest($12::date[])     AS return_date,
           unnest($13::int[])         AS position,
           unnest($14::text[])            AS role,
           unnest($15::text[])    AS origin_label,
           unnest($16::text[]) AS destination_label,
           unnest($17::text[])    AS derived_mode
) AS u
ON CONFLICT (trip_id, todo_key) DO UPDATE SET
    kind = EXCLUDED.kind,
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    provider = EXCLUDED.provider,
    search_url = EXCLUDED.search_url,
    depart_date = EXCLUDED.depart_date,
    return_date = EXCLUDED.return_date,
    position = EXCLUDED.position,
    role = EXCLUDED.role,
    origin_label = EXCLUDED.origin_label,
    destination_label = EXCLUDED.destination_label,
    derived_mode = EXCLUDED.derived_mode
`

type UpsertBookingTodosBatchParams struct {
	TripID            uuid.UUID     `json:"trip_id"`
	Kinds             []string      `json:"kinds"`
	TodoKeys          []string      `json:"todo_keys"`
	Titles            []string      `json:"titles"`
	Subtitles         []string      `json:"subtitles"`
	SubtitleNulls     []bool        `json:"subtitle_nulls"`
	Providers         []string      `json:"providers"`
	ProviderNulls     []bool        `json:"provider_nulls"`
	SearchUrls        []string      `json:"search_urls"`
	SearchUrlNulls    []bool        `json:"search_url_nulls"`
	DepartDates       []pgtype.Date `json:"depart_dates"`
	ReturnDates       []pgtype.Date `json:"return_dates"`
	Positions         []int32       `json:"positions"`
	Roles             []string      `json:"roles"`
	OriginLabels      []string      `json:"origin_labels"`
	DestinationLabels []string      `json:"destination_labels"`
	DerivedModes      []string      `json:"derived_modes"`
}

// Batch twin of UpsertBookingTodo: one round trip for the whole derived set.
// Same column list and the same ON CONFLICT update set — booked, auto, and
// mode are deliberately absent from DO UPDATE, so a re-sync preserves the
// booked flag and the per-leg mode override (and never flips a row's auto
// marker). derived_mode is NOT one of them: it is the server's own answer for
// the leg and is refreshed on every sync, exactly like provider and search_url,
// which the same derivation decides. Nullable date columns ride as
// date[] with NULL elements; the nullable text columns ride as text[] plus a
// parallel bool[] null mask, because sqlc maps text[] to []string, which
// cannot carry NULL elements. The caller must dedupe todo_keys (last
// occurrence wins, like sequential upserts would) — a single INSERT ... ON
// CONFLICT cannot update the same row twice. (Parallel single-array unnest
// calls in one SELECT list expand in lockstep for equal-length arrays;
// sqlc's catalog lacks the multi-array unnest form.)
func (q *Queries) UpsertBookingTodosBatch(ctx context.Context, arg UpsertBookingTodosBatchParams) error {
	_, err := q.db.Exec(ctx, upsertBookingTodosBatch,
		arg.TripID,
		arg.Kinds,
		arg.TodoKeys,
		arg.Titles,
		arg.Subtitles,
		arg.SubtitleNulls,
		arg.Providers,
		arg.ProviderNulls,
		arg.SearchUrls,
		arg.SearchUrlNulls,
		arg.DepartDates,
		arg.ReturnDates,
		arg.Positions,
		arg.Roles,
		arg.OriginLabels,
		arg.DestinationLabels,
		arg.DerivedModes,
	)
	return err
}
