// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Accommodation struct {
	ID        uuid.UUID   `json:"id"`
	TripID    uuid.UUID   `json:"trip_id"`
	Name      string      `json:"name"`
	Provider  *string     `json:"provider"`
	Url       *string     `json:"url"`
	Address   *string     `json:"address"`
	Latitude  *float64    `json:"latitude"`
	Longitude *float64    `json:"longitude"`
	CheckIn   pgtype.Date `json:"check_in"`
	CheckOut  pgtype.Date `json:"check_out"`
	PriceNote *string     `json:"price_note"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	Auto      bool        `json:"auto"`
	AutoKey   *string     `json:"auto_key"`
	Dismissed bool        `json:"dismissed"`
	Position  int32       `json:"position"`
	Booked    bool        `json:"booked"`
}

type AnalyticsEvent struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	EventType string      `json:"event_type"`
	TripID    pgtype.UUID `json:"trip_id"`
	Metadata  []byte      `json:"metadata"`
	CreatedAt time.Time   `json:"created_at"`
}

type AuthIdentity struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	Email          *string   `json:"email"`
	CreatedAt      time.Time `json:"created_at"`
}

type BookingOption struct {
	ID                      uuid.UUID   `json:"id"`
	TripID                  uuid.UUID   `json:"trip_id"`
	BookingTodoID           uuid.UUID   `json:"booking_todo_id"`
	Title                   string      `json:"title"`
	Subtitle                *string     `json:"subtitle"`
	Url                     *string     `json:"url"`
	Provider                *string     `json:"provider"`
	Notes                   *string     `json:"notes"`
	ImageUrl                *string     `json:"image_url"`
	Price                   *float64    `json:"price"`
	Currency                *string     `json:"currency"`
	StartDate               pgtype.Date `json:"start_date"`
	EndDate                 pgtype.Date `json:"end_date"`
	Origin                  *string     `json:"origin"`
	Destination             *string     `json:"destination"`
	Mode                    *string     `json:"mode"`
	PromotedAccommodationID pgtype.UUID `json:"promoted_accommodation_id"`
	PromotedSegmentID       pgtype.UUID `json:"promoted_segment_id"`
	Position                int32       `json:"position"`
	CreatedAt               time.Time   `json:"created_at"`
	UpdatedAt               time.Time   `json:"updated_at"`
}

type BookingTodo struct {
	ID               uuid.UUID   `json:"id"`
	TripID           uuid.UUID   `json:"trip_id"`
	Kind             string      `json:"kind"`
	TodoKey          string      `json:"todo_key"`
	Title            string      `json:"title"`
	Subtitle         *string     `json:"subtitle"`
	Provider         *string     `json:"provider"`
	SearchUrl        *string     `json:"search_url"`
	DepartDate       pgtype.Date `json:"depart_date"`
	ReturnDate       pgtype.Date `json:"return_date"`
	Booked           bool        `json:"booked"`
	Auto             bool        `json:"auto"`
	Position         int32       `json:"position"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	Mode             *string     `json:"mode"`
	Role             *string     `json:"role"`
	OriginLabel      *string     `json:"origin_label"`
	DestinationLabel *string     `json:"destination_label"`
	DerivedMode      *string     `json:"derived_mode"`
	CityLabel        *string     `json:"city_label"`
}

type EmailToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Purpose   string             `json:"purpose"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type HealthSample struct {
	ObservedAt time.Time `json:"observed_at"`
	CoversFrom time.Time `json:"covers_from"`
	Kind       string    `json:"kind"`
	Release    string    `json:"release"`
	GapCause   *string   `json:"gap_cause"`
	DbOk       *bool     `json:"db_ok"`
	AiOk       *bool     `json:"ai_ok"`
	BackupsOk  *bool     `json:"backups_ok"`
}

type ItineraryItem struct {
	ID                    uuid.UUID   `json:"id"`
	TripID                uuid.UUID   `json:"trip_id"`
	Position              int32       `json:"position"`
	Name                  string      `json:"name"`
	PlaceID               *string     `json:"place_id"`
	Address               *string     `json:"address"`
	Latitude              float64     `json:"latitude"`
	Longitude             float64     `json:"longitude"`
	CreatedAt             time.Time   `json:"created_at"`
	Category              *string     `json:"category"`
	TimeOfDay             *string     `json:"time_of_day"`
	City                  *string     `json:"city"`
	DayTripFrom           *string     `json:"day_trip_from"`
	Day                   *int32      `json:"day"`
	LocalSourceName       *string     `json:"local_source_name"`
	LocalRecommendationID pgtype.UUID `json:"local_recommendation_id"`
}

type LocalGuide struct {
	ID           uuid.UUID `json:"id"`
	SourceID     uuid.UUID `json:"source_id"`
	Title        string    `json:"title"`
	City         string    `json:"city"`
	Neighborhood *string   `json:"neighborhood"`
	Body         string    `json:"body"`
	HeroImageUrl *string   `json:"hero_image_url"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type LocalGuideRecommendation struct {
	GuideID          uuid.UUID `json:"guide_id"`
	RecommendationID uuid.UUID `json:"recommendation_id"`
	Position         int32     `json:"position"`
}

type LocalRecommendation struct {
	ID            uuid.UUID `json:"id"`
	SourceID      uuid.UUID `json:"source_id"`
	City          string    `json:"city"`
	Neighborhood  *string   `json:"neighborhood"`
	Name          string    `json:"name"`
	PlaceID       *string   `json:"place_id"`
	Address       *string   `json:"address"`
	Latitude      *float64  `json:"latitude"`
	Longitude     *float64  `json:"longitude"`
	Category      *string   `json:"category"`
	Tip           *string   `json:"tip"`
	Quote         *string   `json:"quote"`
	Tags          []string  `json:"tags"`
	Status        string    `json:"status"`
	PlaceVerified bool      `json:"place_verified"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type LocalSource struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Bio         *string   `json:"bio"`
	PhotoUrl    *string   `json:"photo_url"`
	Location    *string   `json:"location"`
	Expertise   *string   `json:"expertise"`
	Credibility *string   `json:"credibility"`
	ConsentRef  *string   `json:"consent_ref"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type LocalSourceMaterial struct {
	ID        uuid.UUID `json:"id"`
	SourceID  uuid.UUID `json:"source_id"`
	Kind      string    `json:"kind"`
	RawText   string    `json:"raw_text"`
	CreatedAt time.Time `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Type      string             `json:"type"`
	Payload   []byte             `json:"payload"`
	TripID    pgtype.UUID        `json:"trip_id"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type OauthAuthCode struct {
	ID               uuid.UUID          `json:"id"`
	ClientID         uuid.UUID          `json:"client_id"`
	RequestTokenHash string             `json:"request_token_hash"`
	RedirectUri      string             `json:"redirect_uri"`
	Scope            string             `json:"scope"`
	State            string             `json:"state"`
	CodeChallenge    string             `json:"code_challenge"`
	UserID           pgtype.UUID        `json:"user_id"`
	CodeHash         *string            `json:"code_hash"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	CodeUsedAt       pgtype.Timestamptz `json:"code_used_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	CreatedAt        time.Time          `json:"created_at"`
}

type OauthClient struct {
	ID                      uuid.UUID          `json:"id"`
	ClientName              string             `json:"client_name"`
	RedirectUris            []string           `json:"redirect_uris"`
	TokenEndpointAuthMethod string             `json:"token_endpoint_auth_method"`
	CreatedAt               time.Time          `json:"created_at"`
	LastUsedAt              pgtype.Timestamptz `json:"last_used_at"`
}

type OauthGrant struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	ClientID   uuid.UUID          `json:"client_id"`
	Scope      string             `json:"scope"`
	CreatedAt  time.Time          `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type OauthToken struct {
	ID               uuid.UUID          `json:"id"`
	GrantID          uuid.UUID          `json:"grant_id"`
	AuthCodeID       pgtype.UUID        `json:"auth_code_id"`
	AccessTokenHash  string             `json:"access_token_hash"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	AccessExpiresAt  time.Time          `json:"access_expires_at"`
	RefreshExpiresAt time.Time          `json:"refresh_expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        time.Time          `json:"created_at"`
}

type PlanChatSession struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	ChatID       string    `json:"chat_id"`
	Title        string    `json:"title"`
	Preview      string    `json:"preview"`
	Summary      string    `json:"summary"`
	Messages     []byte    `json:"messages"`
	MessageCount int32     `json:"message_count"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ReminderSend struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	TripLineageKey string    `json:"trip_lineage_key"`
	Kind           string    `json:"kind"`
	SentAt         time.Time `json:"sent_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type TravelerPreference struct {
	UserID           uuid.UUID `json:"user_id"`
	Budget           *string   `json:"budget"`
	Pace             *string   `json:"pace"`
	Interests        []string  `json:"interests"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
	HomeAirport      *string   `json:"home_airport"`
	ProfileNotes     *string   `json:"profile_notes"`
	WorkStyle        *string   `json:"work_style"`
	FitnessRoutine   *string   `json:"fitness_routine"`
	OutdoorIntensity *string   `json:"outdoor_intensity"`
	Companions       *string   `json:"companions"`
	Baggage          *string   `json:"baggage"`
}

type Trip struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	Title         string      `json:"title"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	ChatID        *string     `json:"chat_id"`
	Summary       *string     `json:"summary"`
	UpdatedBy     pgtype.UUID `json:"updated_by"`
	TravelMode    *string     `json:"travel_mode"`
	Origin        *string     `json:"origin"`
	OriginAirport *string     `json:"origin_airport"`
	ReturnAirport *string     `json:"return_airport"`
	SummarySource *string     `json:"summary_source"`
}

type TripBudget struct {
	ID           uuid.UUID `json:"id"`
	TripID       uuid.UUID `json:"trip_id"`
	TargetAmount *float64  `json:"target_amount"`
	Currency     string    `json:"currency"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type TripChecklistItem struct {
	ID        uuid.UUID `json:"id"`
	TripID    uuid.UUID `json:"trip_id"`
	Category  string    `json:"category"`
	Title     string    `json:"title"`
	Checked   bool      `json:"checked"`
	Position  int32     `json:"position"`
	Auto      bool      `json:"auto"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TripCollaborator struct {
	ID        uuid.UUID          `json:"id"`
	ChatID    string             `json:"chat_id"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	CreatedAt time.Time          `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type TripExpense struct {
	ID            uuid.UUID   `json:"id"`
	TripID        uuid.UUID   `json:"trip_id"`
	Category      string      `json:"category"`
	Label         string      `json:"label"`
	Amount        float64     `json:"amount"`
	Position      int32       `json:"position"`
	Auto          bool        `json:"auto"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	SourceKind    *string     `json:"source_kind"`
	SourceID      pgtype.UUID `json:"source_id"`
	PlannedAmount *float64    `json:"planned_amount"`
	ActualAmount  *float64    `json:"actual_amount"`
	LegKey        *string     `json:"leg_key"`
	LegPlan       bool        `json:"leg_plan"`
}

type TripInvite struct {
	ID         uuid.UUID          `json:"id"`
	ChatID     string             `json:"chat_id"`
	OwnerID    uuid.UUID          `json:"owner_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  time.Time          `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	AcceptedBy pgtype.UUID        `json:"accepted_by"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type TripRefineSession struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	TripID       uuid.UUID `json:"trip_id"`
	Preview      string    `json:"preview"`
	Summary      string    `json:"summary"`
	Messages     []byte    `json:"messages"`
	MessageCount int32     `json:"message_count"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type TripSegment struct {
	ID          uuid.UUID   `json:"id"`
	TripID      uuid.UUID   `json:"trip_id"`
	Mode        string      `json:"mode"`
	Origin      *string     `json:"origin"`
	Destination *string     `json:"destination"`
	DepartDate  pgtype.Date `json:"depart_date"`
	ArriveDate  pgtype.Date `json:"arrive_date"`
	Provider    *string     `json:"provider"`
	Url         *string     `json:"url"`
	PriceNote   *string     `json:"price_note"`
	Notes       *string     `json:"notes"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	Auto        bool        `json:"auto"`
	AutoKey     *string     `json:"auto_key"`
	Dismissed   bool        `json:"dismissed"`
	Position    int32       `json:"position"`
	Booked      bool        `json:"booked"`
}

type TripShare struct {
	ID        uuid.UUID          `json:"id"`
	ChatID    string             `json:"chat_id"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	Token     string             `json:"token"`
	Role      string             `json:"role"`
	CreatedAt time.Time          `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
	Email             string             `json:"email"`
	PasswordHash      *string            `json:"password_hash"`
	DisplayName       *string            `json:"display_name"`
	IsAdmin           bool               `json:"is_admin"`
	OnboardedAt       pgtype.Timestamptz `json:"onboarded_at"`
	EmailVerifiedAt   pgtype.Timestamptz `json:"email_verified_at"`
	RemindersOptOut   bool               `json:"reminders_opt_out"`
	NudgesOptOut      bool               `json:"nudges_opt_out"`
	LastWeeklyNudgeAt pgtype.Timestamptz `json:"last_weekly_nudge_at"`
	Locale            *string            `json:"locale"`
}
