// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSegment = `-- name: CreateSegment :one
INSERT INTO trip_segments (trip_id, mode, origin, destination, depart_date, arrive_date, provider, url, price_note, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, trip_id, mode, origin, destination, depart_date, arrive_date, provider, url, price_note, notes, created_at, updated_at, auto, auto_key, dismissed, position, booked
`

type CreateSegmentParams struct {
	TripID      uuid.UUID   `json:"trip_id"`
	Mode        string      `json:"mode"`
	Origin      *string     `json:"origin"`
	Destination *string     `json:"destination"`
	DepartDate  pgtype.Date `json:"depart_date"`
	ArriveDate  pgtype.Date `json:"arrive_date"`
	Provider    *string     `json:"provider"`
	Url         *string     `json:"url"`
	PriceNote   *string     `json:"price_note"`
	Notes       *string     `json:"notes"`
}

func (q *Queries) CreateSegment(ctx context.Context, arg CreateSegmentParams) (TripSegment, error) {
	row := q.db.QueryRow(ctx, createSegment,
		arg.TripID,
		arg.Mode,
		arg.Origin,
		arg.Destination,
		arg.DepartDate,
		arg.ArriveDate,
		arg.Provider,
		arg.Url,
		arg.PriceNote,
		arg.Notes,
	)
	var i TripSegment
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Mode,
		&i.Origin,
		&i.Destination,
		&i.DepartDate,
		&i.ArriveDate,
		&i.Provider,
		&i.Url,
		&i.PriceNote,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Auto,
		&i.AutoKey,
		&i.Dismissed,
		&i.Position,
		&i.Booked,
	)
	return i, err
}

const deleteSegment = `-- name: DeleteSegment :execrows
DELETE FROM trip_segments WHERE id = $1 AND trip_id = $2
`

type DeleteSegmentParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteSegment(ctx context.Context, arg DeleteSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSegment, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleDraftSegments = `-- name: DeleteStaleDraftSegments :execrows
DELETE FROM trip_segments
WHERE trip_id = $1 AND auto = true AND (auto_key IS NULL OR auto_key <> ALL($2::text[]))
`

type DeleteStaleDraftSegmentsParams struct {
	TripID uuid.UUID `json:"trip_id"`
	Keys   []string  `json:"keys"`
}

// Prunes drafts (and their tombstones) whose itinerary leg no longer exists;
// never touches confirmed rows.
func (q *Queries) DeleteStaleDraftSegments(ctx context.Context, arg DeleteStaleDraftSegmentsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleDraftSegments, arg.TripID, arg.Keys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dismissDraftSegment = `-- name: DismissDraftSegment :execrows
UPDATE trip_segments SET dismissed = true WHERE id = $1 AND trip_id = $2 AND auto = true
`

type DismissDraftSegmentParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DismissDraftSegment(ctx context.Context, arg DismissDraftSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, dismissDraftSegment, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listConfirmedSegmentsByTrip = `-- name: ListConfirmedSegmentsByTrip :many
SELECT id, trip_id, mode, origin, destination, depart_date, arrive_date, provider, url, price_note, notes, created_at, updated_at, auto, auto_key, dismissed, position, booked FROM trip_segments WHERE trip_id = $1 AND auto = false AND NOT dismissed ORDER BY position ASC, depart_date ASC NULLS LAST, created_at ASC
`

// Viewer/share/duplicate surface: drafts (auto=true) are editor-only.
func (q *Queries) ListConfirmedSegmentsByTrip(ctx context.Context, tripID uuid.UUID) ([]TripSegment, error) {
	rows, err := q.db.Query(ctx, listConfirmedSegmentsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripSegment
	for rows.Next() {
		var i TripSegment
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Mode,
			&i.Origin,
			&i.Destination,
			&i.DepartDate,
			&i.ArriveDate,
			&i.Provider,
			&i.Url,
			&i.PriceNote,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Auto,
			&i.AutoKey,
			&i.Dismissed,
			&i.Position,
			&i.Booked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSegmentsByTrip = `-- name: ListSegmentsByTrip :many
SELECT id, trip_id, mode, origin, destination, depart_date, arrive_date, provider, url, price_note, notes, created_at, updated_at, auto, auto_key, dismissed, position, booked FROM trip_segments WHERE trip_id = $1 AND NOT dismissed ORDER BY position ASC, depart_date ASC NULLS LAST, created_at ASC
`

func (q *Queries) ListSegmentsByTrip(ctx context.Context, tripID uuid.UUID) ([]TripSegment, error) {
	rows, err := q.db.Query(ctx, listSegmentsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripSegment
	for rows.Next() {
		var i TripSegment
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Mode,
			&i.Origin,
			&i.Destination,
			&i.DepartDate,
			&i.ArriveDate,
			&i.Provider,
			&i.Url,
			&i.PriceNote,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Auto,
			&i.AutoKey,
			&i.Dismissed,
			&i.Position,
			&i.Booked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteSegmentFromOption = `-- name: PromoteSegmentFromOption :one
INSERT INTO trip_segments (trip_id, mode, origin, destination, depart_date,
                           arrive_date, provider, url, price_note, notes,
                           auto, auto_key, booked, dismissed, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, false, $11, true, false, 9999)
ON CONFLICT (trip_id, auto_key) WHERE auto_key IS NOT NULL DO UPDATE SET
    mode        = EXCLUDED.mode,
    origin      = EXCLUDED.origin,
    destination = EXCLUDED.destination,
    depart_date = EXCLUDED.depart_date,
    arrive_date = EXCLUDED.arrive_date,
    provider    = EXCLUDED.provider,
    url         = EXCLUDED.url,
    price_note  = EXCLUDED.price_note,
    notes       = EXCLUDED.notes,
    auto        = false,
    dismissed   = false,
    booked      = true
RETURNING id, trip_id, mode, origin, destination, depart_date, arrive_date, provider, url, price_note, notes, created_at, updated_at, auto, auto_key, dismissed, position, booked
`

type PromoteSegmentFromOptionParams struct {
	TripID      uuid.UUID   `json:"trip_id"`
	Mode        string      `json:"mode"`
	Origin      *string     `json:"origin"`
	Destination *string     `json:"destination"`
	DepartDate  pgtype.Date `json:"depart_date"`
	ArriveDate  pgtype.Date `json:"arrive_date"`
	Provider    *string     `json:"provider"`
	Url         *string     `json:"url"`
	PriceNote   *string     `json:"price_note"`
	Notes       *string     `json:"notes"`
	AutoKey     *string     `json:"auto_key"`
}

// Materializes a chosen booking option (00065) as the leg's real transport.
// Same contract as PromoteAccommodationFromOption — see its comment for why
// this upserts on (trip_id, auto_key) with no auto guard, and why stamping
// auto_key is what puts the row in its leg's slot instead of "Other bookings"
// (the matcher tests `autoKey.endsWith('>><label>')` before any fuzzy match).
func (q *Queries) PromoteSegmentFromOption(ctx context.Context, arg PromoteSegmentFromOptionParams) (TripSegment, error) {
	row := q.db.QueryRow(ctx, promoteSegmentFromOption,
		arg.TripID,
		arg.Mode,
		arg.Origin,
		arg.Destination,
		arg.DepartDate,
		arg.ArriveDate,
		arg.Provider,
		arg.Url,
		arg.PriceNote,
		arg.Notes,
		arg.AutoKey,
	)
	var i TripSegment
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Mode,
		&i.Origin,
		&i.Destination,
		&i.DepartDate,
		&i.ArriveDate,
		&i.Provider,
		&i.Url,
		&i.PriceNote,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Auto,
		&i.AutoKey,
		&i.Dismissed,
		&i.Position,
		&i.Booked,
	)
	return i, err
}

const setSegmentPosition = `-- name: SetSegmentPosition :exec
UPDATE trip_segments SET position = $3 WHERE id = $1 AND trip_id = $2
`

type SetSegmentPositionParams struct {
	ID       uuid.UUID `json:"id"`
	TripID   uuid.UUID `json:"trip_id"`
	Position int32     `json:"position"`
}

func (q *Queries) SetSegmentPosition(ctx context.Context, arg SetSegmentPositionParams) error {
	_, err := q.db.Exec(ctx, setSegmentPosition, arg.ID, arg.TripID, arg.Position)
	return err
}

const shiftSegmentDates = `-- name: ShiftSegmentDates :execrows
UPDATE trip_segments
SET depart_date = depart_date + $1::int,
    arrive_date = arrive_date + $1::int
WHERE trip_id = $2
  AND (depart_date IS NOT NULL OR arrive_date IS NOT NULL)
`

type ShiftSegmentDatesParams struct {
	Days   int32     `json:"days"`
	TripID uuid.UUID `json:"trip_id"`
}

// Whole-trip date shift (agent set_trip_dates); see ShiftAccommodationDates.
func (q *Queries) ShiftSegmentDates(ctx context.Context, arg ShiftSegmentDatesParams) (int64, error) {
	result, err := q.db.Exec(ctx, shiftSegmentDates, arg.Days, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const shiftSegmentDatesFrom = `-- name: ShiftSegmentDatesFrom :execrows
UPDATE trip_segments
SET depart_date = depart_date + $1::int,
    arrive_date = arrive_date + $1::int
WHERE trip_id = $2
  AND COALESCE(arrive_date, depart_date) >= $3::date
`

type ShiftSegmentDatesFromParams struct {
	Days     int32       `json:"days"`
	TripID   uuid.UUID   `json:"trip_id"`
	FromDate pgtype.Date `json:"from_date"`
}

// Suffix date shift (agent shift_days_from): ShiftSegmentDates with a date
// floor. Unlike ShiftAccommodationDatesFrom this moves a segment AS A UNIT,
// membership decided by its arrival (fallback departure): a segment's two
// dates are one physical journey (specs/overnight-arrivals), so an overnight
// ride into the pivot city departs later too rather than being stretched
// across the shift. A journey is part of the suffix when it LANDS in it.
// Raw UPDATE: auto drafts shift without being confirmed. Undated segments
// don't move and aren't counted.
func (q *Queries) ShiftSegmentDatesFrom(ctx context.Context, arg ShiftSegmentDatesFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, shiftSegmentDatesFrom, arg.Days, arg.TripID, arg.FromDate)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSegment = `-- name: UpdateSegment :one
UPDATE trip_segments
SET mode        = COALESCE($1, mode),
    origin      = COALESCE($2, origin),
    destination = COALESCE($3, destination),
    depart_date = COALESCE($4, depart_date),
    arrive_date = COALESCE($5, arrive_date),
    provider    = COALESCE($6, provider),
    url         = COALESCE($7, url),
    price_note  = COALESCE($8, price_note),
    notes       = COALESCE($9, notes),
    booked      = COALESCE($10, booked),
    auto        = false
WHERE id = $11 AND trip_id = $12 AND NOT dismissed
RETURNING id, trip_id, mode, origin, destination, depart_date, arrive_date, provider, url, price_note, notes, created_at, updated_at, auto, auto_key, dismissed, position, booked
`

type UpdateSegmentParams struct {
	Mode        *string     `json:"mode"`
	Origin      *string     `json:"origin"`
	Destination *string     `json:"destination"`
	DepartDate  pgtype.Date `json:"depart_date"`
	ArriveDate  pgtype.Date `json:"arrive_date"`
	Provider    *string     `json:"provider"`
	Url         *string     `json:"url"`
	PriceNote   *string     `json:"price_note"`
	Notes       *string     `json:"notes"`
	Booked      *bool       `json:"booked"`
	ID          uuid.UUID   `json:"id"`
	TripID      uuid.UUID   `json:"trip_id"`
}

// Partial update (COALESCE sqlc.narg idiom, see query/trips.sql UpdateTrip).
// Any edit confirms a draft (auto = false), taking it out of sync ownership.
// COALESCE means fields can be overwritten but not cleared back to NULL.
func (q *Queries) UpdateSegment(ctx context.Context, arg UpdateSegmentParams) (TripSegment, error) {
	row := q.db.QueryRow(ctx, updateSegment,
		arg.Mode,
		arg.Origin,
		arg.Destination,
		arg.DepartDate,
		arg.ArriveDate,
		arg.Provider,
		arg.Url,
		arg.PriceNote,
		arg.Notes,
		arg.Booked,
		arg.ID,
		arg.TripID,
	)
	var i TripSegment
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Mode,
		&i.Origin,
		&i.Destination,
		&i.DepartDate,
		&i.ArriveDate,
		&i.Provider,
		&i.Url,
		&i.PriceNote,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Auto,
		&i.AutoKey,
		&i.Dismissed,
		&i.Position,
		&i.Booked,
	)
	return i, err
}

const upsertDraftSegment = `-- name: UpsertDraftSegment :execrows
INSERT INTO trip_segments (trip_id, mode, origin, destination, depart_date, auto, auto_key)
VALUES ($1, $2, $3, $4, $5, true, $6)
ON CONFLICT (trip_id, auto_key) WHERE auto_key IS NOT NULL DO UPDATE SET
    mode        = EXCLUDED.mode,
    origin      = EXCLUDED.origin,
    destination = EXCLUDED.destination,
    depart_date = EXCLUDED.depart_date
WHERE trip_segments.auto AND NOT trip_segments.dismissed
`

type UpsertDraftSegmentParams struct {
	TripID      uuid.UUID   `json:"trip_id"`
	Mode        string      `json:"mode"`
	Origin      *string     `json:"origin"`
	Destination *string     `json:"destination"`
	DepartDate  pgtype.Date `json:"depart_date"`
	AutoKey     *string     `json:"auto_key"`
}

// The WHERE guard leaves confirmed (auto=false) and dismissed rows untouched,
// so this must be :execrows — a skipped conflict returns no row.
func (q *Queries) UpsertDraftSegment(ctx context.Context, arg UpsertDraftSegmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertDraftSegment,
		arg.TripID,
		arg.Mode,
		arg.Origin,
		arg.Destination,
		arg.DepartDate,
		arg.AutoKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
