// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trips.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeItineraryItemPositionGap = `-- name: CloseItineraryItemPositionGap :exec
UPDATE itinerary_items SET position = position - 1
WHERE trip_id = $1 AND position > $2
`

type CloseItineraryItemPositionGapParams struct {
	TripID   uuid.UUID `json:"trip_id"`
	Position int32     `json:"position"`
}

// Compacts positions after a delete (mirror of ShiftItineraryItemPositions).
func (q *Queries) CloseItineraryItemPositionGap(ctx context.Context, arg CloseItineraryItemPositionGapParams) error {
	_, err := q.db.Exec(ctx, closeItineraryItemPositionGap, arg.TripID, arg.Position)
	return err
}

const countActiveTripLineagesByOwner = `-- name: CountActiveTripLineagesByOwner :one
SELECT count(DISTINCT COALESCE(chat_id, id::text)) FROM trips WHERE user_id = $1
`

// Active trips for the free-cap signal (specs/free-cap-instrumentation):
// one per chat lineage, the same COALESCE(chat_id, id::text) grouping
// ListLatestTripsByOwner's DISTINCT ON uses — new versions of an existing
// lineage don't add to the count. All saved trips count as active (no
// archived status exists today).
func (q *Queries) CountActiveTripLineagesByOwner(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTripLineagesByOwner, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createItineraryItem = `-- name: CreateItineraryItem :one
INSERT INTO itinerary_items (trip_id, position, name, place_id, address, latitude, longitude, category, time_of_day, city, day_trip_from, day, local_source_name, local_recommendation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, trip_id, position, name, place_id, address, latitude, longitude, created_at, category, time_of_day, city, day_trip_from, day, local_source_name, local_recommendation_id
`

type CreateItineraryItemParams struct {
	TripID                uuid.UUID   `json:"trip_id"`
	Position              int32       `json:"position"`
	Name                  string      `json:"name"`
	PlaceID               *string     `json:"place_id"`
	Address               *string     `json:"address"`
	Latitude              float64     `json:"latitude"`
	Longitude             float64     `json:"longitude"`
	Category              *string     `json:"category"`
	TimeOfDay             *string     `json:"time_of_day"`
	City                  *string     `json:"city"`
	DayTripFrom           *string     `json:"day_trip_from"`
	Day                   *int32      `json:"day"`
	LocalSourceName       *string     `json:"local_source_name"`
	LocalRecommendationID pgtype.UUID `json:"local_recommendation_id"`
}

func (q *Queries) CreateItineraryItem(ctx context.Context, arg CreateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, createItineraryItem,
		arg.TripID,
		arg.Position,
		arg.Name,
		arg.PlaceID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Category,
		arg.TimeOfDay,
		arg.City,
		arg.DayTripFrom,
		arg.Day,
		arg.LocalSourceName,
		arg.LocalRecommendationID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Position,
		&i.Name,
		&i.PlaceID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.Category,
		&i.TimeOfDay,
		&i.City,
		&i.DayTripFrom,
		&i.Day,
		&i.LocalSourceName,
		&i.LocalRecommendationID,
	)
	return i, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (user_id, title, chat_id, summary, summary_source, travel_mode, origin, origin_airport, return_airport, updated_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $1)
RETURNING id, user_id, created_at, updated_at, title, start_date, end_date, chat_id, summary, updated_by, travel_mode, origin, origin_airport, return_airport, summary_source
`

type CreateTripParams struct {
	UserID        uuid.UUID `json:"user_id"`
	Title         string    `json:"title"`
	ChatID        *string   `json:"chat_id"`
	Summary       *string   `json:"summary"`
	SummarySource *string   `json:"summary_source"`
	TravelMode    *string   `json:"travel_mode"`
	Origin        *string   `json:"origin"`
	OriginAirport *string   `json:"origin_airport"`
	ReturnAirport *string   `json:"return_airport"`
}

// origin / origin_airport / return_airport are set here and by SetTripEndpoints
// (the agent's set_trip_origin tool) — and nowhere else. They stay out of
// UpdateTrip's COALESCE set so PATCH cannot move them: a departure airport is
// not a field to be poked at, it is a change that has to travel with the trip's
// derived legs (see 00064 and TestPatchTripCannotSetOrigin).
func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.UserID,
		arg.Title,
		arg.ChatID,
		arg.Summary,
		arg.SummarySource,
		arg.TravelMode,
		arg.Origin,
		arg.OriginAirport,
		arg.ReturnAirport,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.ChatID,
		&i.Summary,
		&i.UpdatedBy,
		&i.TravelMode,
		&i.Origin,
		&i.OriginAirport,
		&i.ReturnAirport,
		&i.SummarySource,
	)
	return i, err
}

const deleteItineraryItem = `-- name: DeleteItineraryItem :execrows
DELETE FROM itinerary_items WHERE id = $1 AND trip_id = $2
`

type DeleteItineraryItemParams struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) DeleteItineraryItem(ctx context.Context, arg DeleteItineraryItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItineraryItem, arg.ID, arg.TripID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteItineraryItemsByTrip = `-- name: DeleteItineraryItemsByTrip :exec
DELETE FROM itinerary_items WHERE trip_id = $1
`

func (q *Queries) DeleteItineraryItemsByTrip(ctx context.Context, tripID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteItineraryItemsByTrip, tripID)
	return err
}

const deleteTrip = `-- name: DeleteTrip :execrows
DELETE FROM trips t
WHERE t.user_id = $1
  AND (
    t.id = $2
    OR t.chat_id = (
      SELECT chat_id FROM trips
      WHERE id = $2 AND user_id = $1 AND chat_id IS NOT NULL
    )
  )
`

type DeleteTripParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

// Deletes the trip and, when it belongs to a chat group, all its versions.
// Legacy trips (chat_id NULL) match only by id, so a single row is removed.
func (q *Queries) DeleteTrip(ctx context.Context, arg DeleteTripParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrip, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getItineraryItemsByTrip = `-- name: GetItineraryItemsByTrip :many
SELECT id, trip_id, position, name, place_id, address, latitude, longitude, created_at, category, time_of_day, city, day_trip_from, day, local_source_name, local_recommendation_id FROM itinerary_items WHERE trip_id = $1 ORDER BY position ASC
`

func (q *Queries) GetItineraryItemsByTrip(ctx context.Context, tripID uuid.UUID) ([]ItineraryItem, error) {
	rows, err := q.db.Query(ctx, getItineraryItemsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItineraryItem
	for rows.Next() {
		var i ItineraryItem
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Position,
			&i.Name,
			&i.PlaceID,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.Category,
			&i.TimeOfDay,
			&i.City,
			&i.DayTripFrom,
			&i.Day,
			&i.LocalSourceName,
			&i.LocalRecommendationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestTripSummaryByChat = `-- name: GetLatestTripSummaryByChat :one
SELECT summary, summary_source FROM trips
WHERE user_id = $1 AND chat_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestTripSummaryByChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID *string   `json:"chat_id"`
}

type GetLatestTripSummaryByChatRow struct {
	Summary       *string `json:"summary"`
	SummarySource *string `json:"summary_source"`
}

// The newest version's description in a chat lineage. persistTrip reads it to
// carry the prose forward when a version save supplies none: every save INSERTs
// a new row, so without this a re-save silently drops the description — reachable
// today with no UPDATE statement existing anywhere.
func (q *Queries) GetLatestTripSummaryByChat(ctx context.Context, arg GetLatestTripSummaryByChatParams) (GetLatestTripSummaryByChatRow, error) {
	row := q.db.QueryRow(ctx, getLatestTripSummaryByChat, arg.UserID, arg.ChatID)
	var i GetLatestTripSummaryByChatRow
	err := row.Scan(&i.Summary, &i.SummarySource)
	return i, err
}

const getTripByIDAndOwner = `-- name: GetTripByIDAndOwner :one
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, chat_id, summary, updated_by, travel_mode, origin, origin_airport, return_airport, summary_source FROM trips WHERE id = $1 AND user_id = $2
`

type GetTripByIDAndOwnerParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTripByIDAndOwner(ctx context.Context, arg GetTripByIDAndOwnerParams) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripByIDAndOwner, arg.ID, arg.UserID)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.ChatID,
		&i.Summary,
		&i.UpdatedBy,
		&i.TravelMode,
		&i.Origin,
		&i.OriginAirport,
		&i.ReturnAirport,
		&i.SummarySource,
	)
	return i, err
}

const getTripForUpdate = `-- name: GetTripForUpdate :one
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, chat_id, summary, updated_by, travel_mode, origin, origin_airport, return_airport, summary_source FROM trips WHERE id = $1 FOR UPDATE
`

// Row-locks the trip for the duration of the transaction. Full-itinerary
// rewrites (replaceTripSection) and reorders read-then-write the whole item
// set; without this lock two concurrent writers interleave under READ
// COMMITTED and both item sets survive the delete/reinsert.
func (q *Queries) GetTripForUpdate(ctx context.Context, id uuid.UUID) (Trip, error) {
	row := q.db.QueryRow(ctx, getTripForUpdate, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.ChatID,
		&i.Summary,
		&i.UpdatedBy,
		&i.TravelMode,
		&i.Origin,
		&i.OriginAirport,
		&i.ReturnAirport,
		&i.SummarySource,
	)
	return i, err
}

const getTripStatusByID = `-- name: GetTripStatusByID :one
SELECT t.updated_at, t.updated_by,
       COALESCE(u.display_name, '')::text AS updated_by_name
FROM trips t
LEFT JOIN users u ON u.id = t.updated_by
WHERE t.id = $1
  AND (t.user_id = $2 OR EXISTS (
        SELECT 1 FROM trip_collaborators c
        WHERE c.user_id = $2 AND c.revoked_at IS NULL
          AND c.owner_id = t.user_id AND c.chat_id = t.chat_id))
`

type GetTripStatusByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetTripStatusByIDRow struct {
	UpdatedAt     time.Time   `json:"updated_at"`
	UpdatedBy     pgtype.UUID `json:"updated_by"`
	UpdatedByName string      `json:"updated_by_name"`
}

// Freshness poll for shared-trip clients: one cheap row, authorized for the
// owner or any active collaborator on the row's lineage.
func (q *Queries) GetTripStatusByID(ctx context.Context, arg GetTripStatusByIDParams) (GetTripStatusByIDRow, error) {
	row := q.db.QueryRow(ctx, getTripStatusByID, arg.ID, arg.UserID)
	var i GetTripStatusByIDRow
	err := row.Scan(&i.UpdatedAt, &i.UpdatedBy, &i.UpdatedByName)
	return i, err
}

const hasActiveCollaborators = `-- name: HasActiveCollaborators :one
SELECT EXISTS (
  SELECT 1 FROM trip_collaborators
  WHERE owner_id = $1 AND chat_id = $2 AND revoked_at IS NULL
)::bool
`

type HasActiveCollaboratorsParams struct {
	OwnerID uuid.UUID `json:"owner_id"`
	ChatID  string    `json:"chat_id"`
}

// Whether anyone collaborates on this lineage — tells the owner's client the
// trip is shared (worth polling for freshness).
func (q *Queries) HasActiveCollaborators(ctx context.Context, arg HasActiveCollaboratorsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveCollaborators, arg.OwnerID, arg.ChatID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listLatestTripsByOwner = `-- name: ListLatestTripsByOwner :many
SELECT latest.id, latest.user_id, latest.created_at, latest.updated_at,
       latest.title, latest.start_date, latest.end_date,
       latest.chat_id, latest.summary, latest.version_count,
       COALESCE(c.cities, ARRAY[]::text[])::text[] AS cities,
       COALESCE(c.city_pins, '[]'::jsonb) AS city_pins,
       COALESCE(ic.item_count, 0)::int AS item_count,
       COALESCE(bt.total, 0)::int AS booking_total,
       COALESCE(bt.booked, 0)::int AS booking_booked,
       bt.next_transport_depart::date AS next_transport_depart,
       COALESCE(st.total, 0)::int AS stay_total,
       COALESCE(st.booked, 0)::int AS stay_booked,
       COALESCE(pk.total, 0)::int AS packing_total,
       COALESCE(pk.done, 0)::int AS packing_done,
       tb.target_amount AS budget_target,
       COALESCE(ex.spent, 0)::float8 AS budget_spent,
       COALESCE(tb.currency, 'USD')::text AS budget_currency,
       EXISTS (
         SELECT 1 FROM trip_collaborators tc
         WHERE tc.owner_id = latest.user_id AND tc.chat_id = latest.chat_id
           AND tc.revoked_at IS NULL
       )::bool AS shared
FROM (
  SELECT DISTINCT ON (COALESCE(chat_id, id::text))
         id, user_id, created_at, updated_at, title, start_date, end_date, chat_id, summary,
         count(*) OVER (PARTITION BY COALESCE(chat_id, id::text)) AS version_count
  FROM trips WHERE trips.user_id = $1
  ORDER BY COALESCE(chat_id, id::text), created_at DESC
) latest
LEFT JOIN LATERAL (
  SELECT array_agg(hub.city ORDER BY hub.first_pos) AS cities,
         jsonb_agg(jsonb_build_object('city', hub.city, 'lat', hub.lat, 'lng', hub.lng)
                   ORDER BY hub.first_pos)
           FILTER (WHERE hub.lat IS NOT NULL) AS city_pins
  FROM (
    SELECT COALESCE(NULLIF(ii.day_trip_from, ''), NULLIF(ii.city, '')) AS city,
           MIN(ii.position) AS first_pos,
           (array_agg(ii.latitude ORDER BY ii.position)
              FILTER (WHERE ii.latitude <> 0 OR ii.longitude <> 0))[1] AS lat,
           (array_agg(ii.longitude ORDER BY ii.position)
              FILTER (WHERE ii.latitude <> 0 OR ii.longitude <> 0))[1] AS lng
    FROM itinerary_items ii
    WHERE ii.trip_id = latest.id
      AND COALESCE(NULLIF(ii.day_trip_from, ''), NULLIF(ii.city, '')) IS NOT NULL
    GROUP BY COALESCE(NULLIF(ii.day_trip_from, ''), NULLIF(ii.city, ''))
  ) hub
) c ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS item_count
  FROM itinerary_items ii2 WHERE ii2.trip_id = latest.id
) ic ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS total, count(*) FILTER (WHERE b.booked) AS booked,
         min(b.depart_date) FILTER (WHERE NOT b.booked AND b.kind = 'transport'
                                      AND b.depart_date >= CURRENT_DATE) AS next_transport_depart
  FROM booking_todos b WHERE b.trip_id = latest.id
) bt ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS total, count(*) FILTER (WHERE a.booked) AS booked
  FROM accommodations a
  WHERE a.trip_id = latest.id AND a.auto = false AND NOT a.dismissed
) st ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS total, count(*) FILTER (WHERE ck.checked) AS done
  FROM trip_checklist_items ck WHERE ck.trip_id = latest.id
) pk ON true
LEFT JOIN trip_budgets tb ON tb.trip_id = latest.id
LEFT JOIN LATERAL (
  -- actual_amount, NOT amount: since 00067 ` + "`" + `amount` + "`" + ` is
  -- COALESCE(actual, planned), so summing it here would quietly fold money the
  -- traveler has only PLANNED into a pill labelled "spent" — and the Budget tab
  -- would report a different number for the same trip, with no error anywhere.
  -- budget_spent means money actually spent, exactly as buildBudgetResponse's
  -- ` + "`" + `spent` + "`" + ` does. Pinned by TestListRowBudgetMatchesBudgetEndpoint.
  SELECT sum(e.actual_amount) AS spent FROM trip_expenses e WHERE e.trip_id = latest.id
) ex ON true
ORDER BY latest.created_at DESC
`

type ListLatestTripsByOwnerRow struct {
	ID                  uuid.UUID   `json:"id"`
	UserID              uuid.UUID   `json:"user_id"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	Title               string      `json:"title"`
	StartDate           pgtype.Date `json:"start_date"`
	EndDate             pgtype.Date `json:"end_date"`
	ChatID              *string     `json:"chat_id"`
	Summary             *string     `json:"summary"`
	VersionCount        int64       `json:"version_count"`
	Cities              []string    `json:"cities"`
	CityPins            []byte      `json:"city_pins"`
	ItemCount           int32       `json:"item_count"`
	BookingTotal        int32       `json:"booking_total"`
	BookingBooked       int32       `json:"booking_booked"`
	NextTransportDepart pgtype.Date `json:"next_transport_depart"`
	StayTotal           int32       `json:"stay_total"`
	StayBooked          int32       `json:"stay_booked"`
	PackingTotal        int32       `json:"packing_total"`
	PackingDone         int32       `json:"packing_done"`
	BudgetTarget        *float64    `json:"budget_target"`
	BudgetSpent         float64     `json:"budget_spent"`
	BudgetCurrency      string      `json:"budget_currency"`
	Shared              bool        `json:"shared"`
}

// One row per chat group (latest version), with how many versions exist and the
// trip's distinct hub cities (day_trip_from ?? city) in first-appearance order
// for a location summary. Legacy trips with NULL chat_id stand alone.
//
// List-row enrichment invariant: the list payload stays ONE query — anything
// added here must be a lateral / correlated subquery over indexed FKs (no
// N+1, no per-trip HTTP fanout). Facts that can't be expressed that way
// (trip health, the next-step ladder) stay off the list. The shared EXISTS
// is the HasActiveCollaborators predicate — keep the two in sync.
//
// Lateral semantics (specs/trips-page-insights):
//
//	c  — ONE itinerary scan emits both cities and city_pins, so pins are a
//	     subset of cities in the same first-appearance order structurally.
//	     A hub's pin is its first item by position with non-(0,0) coords —
//	     itinerary_items.latitude/longitude are NOT NULL with (0,0) as the
//	     no-location sentinel (the computeTripLegs rule); a hub with only
//	     sentinel items appears in cities but never in city_pins.
//	bt — booking-todo progress + next_transport_depart, the earliest
//	     UNBOOKED future TRANSPORT depart date (the booking-urgency nudge).
//	st — CONFIRMED stays only (auto = false AND NOT dismissed, the
//	     ListConfirmedAccommodationsByTrip rule — drafts churn with the
//	     itinerary sync and would make the count flap).
//	pk — packing-checklist progress.
//	tb/ex — budget target+currency and PAID expense sum, joined SEPARATELY so a
//	     trip with expenses but no budget row still reports spent; currency
//	     defaults to USD, matching buildBudgetResponse (single-currency by
//	     design — no FX).
func (q *Queries) ListLatestTripsByOwner(ctx context.Context, userID uuid.UUID) ([]ListLatestTripsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listLatestTripsByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestTripsByOwnerRow
	for rows.Next() {
		var i ListLatestTripsByOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.ChatID,
			&i.Summary,
			&i.VersionCount,
			&i.Cities,
			&i.CityPins,
			&i.ItemCount,
			&i.BookingTotal,
			&i.BookingBooked,
			&i.NextTransportDepart,
			&i.StayTotal,
			&i.StayBooked,
			&i.PackingTotal,
			&i.PackingDone,
			&i.BudgetTarget,
			&i.BudgetSpent,
			&i.BudgetCurrency,
			&i.Shared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripVersionsByChat = `-- name: ListTripVersionsByChat :many
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, chat_id, summary, updated_by, travel_mode, origin, origin_airport, return_airport, summary_source FROM trips WHERE user_id = $1 AND chat_id = $2 ORDER BY created_at DESC
`

type ListTripVersionsByChatParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID *string   `json:"chat_id"`
}

func (q *Queries) ListTripVersionsByChat(ctx context.Context, arg ListTripVersionsByChatParams) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripVersionsByChat, arg.UserID, arg.ChatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.ChatID,
			&i.Summary,
			&i.UpdatedBy,
			&i.TravelMode,
			&i.Origin,
			&i.OriginAirport,
			&i.ReturnAirport,
			&i.SummarySource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTripsByOwner = `-- name: ListTripsByOwner :many
SELECT id, user_id, created_at, updated_at, title, start_date, end_date, chat_id, summary, updated_by, travel_mode, origin, origin_airport, return_airport, summary_source FROM trips WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTripsByOwner(ctx context.Context, userID uuid.UUID) ([]Trip, error) {
	rows, err := q.db.Query(ctx, listTripsByOwner, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trip
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.ChatID,
			&i.Summary,
			&i.UpdatedBy,
			&i.TravelMode,
			&i.Origin,
			&i.OriginAirport,
			&i.ReturnAirport,
			&i.SummarySource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTripDates = `-- name: SetTripDates :exec
UPDATE trips SET start_date = $2, end_date = $3 WHERE id = $1
`

type SetTripDatesParams struct {
	ID        uuid.UUID   `json:"id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

// Authorization happens in the caller (runSetTripDatesTool's resolution
// ladder), same as SetTripTravelMode — no user_id scope here, so editor
// collaborators can shift a shared trip.
func (q *Queries) SetTripDates(ctx context.Context, arg SetTripDatesParams) error {
	_, err := q.db.Exec(ctx, setTripDates, arg.ID, arg.StartDate, arg.EndDate)
	return err
}

const setTripEndpoints = `-- name: SetTripEndpoints :one
UPDATE trips
SET origin = $1,
    origin_airport = $2,
    return_airport = $3
WHERE id = $4
RETURNING id, user_id, created_at, updated_at, title, start_date, end_date, chat_id, summary, updated_by, travel_mode, origin, origin_airport, return_airport, summary_source
`

type SetTripEndpointsParams struct {
	Origin        *string   `json:"origin"`
	OriginAirport *string   `json:"origin_airport"`
	ReturnAirport *string   `json:"return_airport"`
	ID            uuid.UUID `json:"id"`
}

// The ONE writer of a saved trip's departure/return endpoints. Deliberately
// unscoped by user_id, like SetTripDates: the caller authorizes (owner or
// editor collaborator, via resolveDateShiftTrip).
//
// The two airports are written TOGETHER, always. NULL never means "same as the
// other direction" — a default nobody can see is what put an EWR leg on a trip
// leaving from Albany — it means only that this trip states no airport, and the
// legs fall back to trips.origin and then the owner's saved home airport.
// CHECK trips_endpoint_airport_pair (00064) makes that a DB invariant.
func (q *Queries) SetTripEndpoints(ctx context.Context, arg SetTripEndpointsParams) (Trip, error) {
	row := q.db.QueryRow(ctx, setTripEndpoints,
		arg.Origin,
		arg.OriginAirport,
		arg.ReturnAirport,
		arg.ID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.ChatID,
		&i.Summary,
		&i.UpdatedBy,
		&i.TravelMode,
		&i.Origin,
		&i.OriginAirport,
		&i.ReturnAirport,
		&i.SummarySource,
	)
	return i, err
}

const setTripSummary = `-- name: SetTripSummary :exec
UPDATE trips SET summary = $1, summary_source = $2
WHERE id = $3
`

type SetTripSummaryParams struct {
	Summary       *string   `json:"summary"`
	SummarySource *string   `json:"summary_source"`
	ID            uuid.UUID `json:"id"`
}

// The ONE writer of a saved trip's description after creation (00071,
// specs/trip-description) — called by applyTripSummary for both the trip page's
// PATCH and the chat's set_trip_description. Authorization happens in the
// callers (editableTrip / resolveDateShiftTrip), same as SetTripDates, so editor
// collaborators can write.
//
// Plain narg rather than UpdateTrip's COALESCE, deliberately: COALESCE cannot
// carry "write NULL", so a description could be set and replaced but never
// CLEARED (the limitation PatchTripRequest.TravelMode's comment laments and
// query/preferences.sql's clear_home_airport flag was written to escape). The two
// columns move together — a description and whose words it is are one fact.
func (q *Queries) SetTripSummary(ctx context.Context, arg SetTripSummaryParams) error {
	_, err := q.db.Exec(ctx, setTripSummary, arg.Summary, arg.SummarySource, arg.ID)
	return err
}

const setTripTravelMode = `-- name: SetTripTravelMode :exec
UPDATE trips SET travel_mode = $2 WHERE id = $1
`

type SetTripTravelModeParams struct {
	ID         uuid.UUID `json:"id"`
	TravelMode *string   `json:"travel_mode"`
}

// Authorization happens in the callers (checkBoundTripSession / editableTrip),
// same as CreateSegment — no user_id scope here.
func (q *Queries) SetTripTravelMode(ctx context.Context, arg SetTripTravelModeParams) error {
	_, err := q.db.Exec(ctx, setTripTravelMode, arg.ID, arg.TravelMode)
	return err
}

const shiftItineraryItemDaysFrom = `-- name: ShiftItineraryItemDaysFrom :execrows
UPDATE itinerary_items
SET day = day + $1::int
WHERE trip_id = $2 AND day >= $3::int
`

type ShiftItineraryItemDaysFromParams struct {
	Days    int32     `json:"days"`
	TripID  uuid.UUID `json:"trip_id"`
	FromDay int32     `json:"from_day"`
}

// Suffix day shift (agent shift_days_from): every item on or after the pivot
// day moves by the delta; earlier and undated items stay put and are not
// counted. The set_trip_dates Shift* family with a day floor.
func (q *Queries) ShiftItineraryItemDaysFrom(ctx context.Context, arg ShiftItineraryItemDaysFromParams) (int64, error) {
	result, err := q.db.Exec(ctx, shiftItineraryItemDaysFrom, arg.Days, arg.TripID, arg.FromDay)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const shiftItineraryItemPositions = `-- name: ShiftItineraryItemPositions :exec
UPDATE itinerary_items SET position = position + 1
WHERE trip_id = $1 AND position >= $2
`

type ShiftItineraryItemPositionsParams struct {
	TripID   uuid.UUID `json:"trip_id"`
	Position int32     `json:"position"`
}

// Opens a gap at the given position for an insert; the (trip_id, position)
// index is non-unique, so the unordered update cannot collide.
func (q *Queries) ShiftItineraryItemPositions(ctx context.Context, arg ShiftItineraryItemPositionsParams) error {
	_, err := q.db.Exec(ctx, shiftItineraryItemPositions, arg.TripID, arg.Position)
	return err
}

const touchTrip = `-- name: TouchTrip :exec
UPDATE trips SET updated_at = now(), updated_by = $2 WHERE id = $1
`

type TouchTripParams struct {
	ID        uuid.UUID   `json:"id"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

// Content writes don't touch the trips row, so bump updated_at by hand and
// record who made the edit (the "Updated by X" attribution on shared trips).
// INVARIANT: only call from real user edits — never from passive load paths
// like syncBookingTodos, or every reader looks like an editor and polling
// clients chase each other's refreshes.
func (q *Queries) TouchTrip(ctx context.Context, arg TouchTripParams) error {
	_, err := q.db.Exec(ctx, touchTrip, arg.ID, arg.UpdatedBy)
	return err
}

const tripLineageExists = `-- name: TripLineageExists :one
SELECT EXISTS(
  SELECT 1 FROM trips WHERE user_id = $1 AND chat_id = $2
) AS lineage_exists
`

type TripLineageExistsParams struct {
	UserID uuid.UUID `json:"user_id"`
	ChatID *string   `json:"chat_id"`
}

// Whether the owner already has any trip in this chat lineage. persistTrip
// runs it inside the same transaction as its insert to distinguish a
// brand-new lineage from a new version of an existing one: the free-cap
// active_trips signal may only fire for new lineages (a version save never
// moves the lineage count and can never emit —
// specs/free-cap-instrumentation).
func (q *Queries) TripLineageExists(ctx context.Context, arg TripLineageExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, tripLineageExists, arg.UserID, arg.ChatID)
	var lineage_exists bool
	err := row.Scan(&lineage_exists)
	return lineage_exists, err
}

const updateItineraryItem = `-- name: UpdateItineraryItem :one
UPDATE itinerary_items
SET name        = COALESCE($1, name),
    place_id    = COALESCE($2, place_id),
    address     = COALESCE($3, address),
    latitude    = COALESCE($4, latitude),
    longitude   = COALESCE($5, longitude),
    category    = COALESCE($6, category),
    time_of_day = COALESCE($7, time_of_day),
    city        = COALESCE($8, city),
    day_trip_from = COALESCE($9, day_trip_from),
    day         = COALESCE($10, day)
WHERE id = $11 AND trip_id = $12
RETURNING id, trip_id, position, name, place_id, address, latitude, longitude, created_at, category, time_of_day, city, day_trip_from, day, local_source_name, local_recommendation_id
`

type UpdateItineraryItemParams struct {
	Name        *string   `json:"name"`
	PlaceID     *string   `json:"place_id"`
	Address     *string   `json:"address"`
	Latitude    *float64  `json:"latitude"`
	Longitude   *float64  `json:"longitude"`
	Category    *string   `json:"category"`
	TimeOfDay   *string   `json:"time_of_day"`
	City        *string   `json:"city"`
	DayTripFrom *string   `json:"day_trip_from"`
	Day         *int32    `json:"day"`
	ID          uuid.UUID `json:"id"`
	TripID      uuid.UUID `json:"trip_id"`
}

// Partial update (COALESCE narg pattern, like UpdateTrip). Attribution columns
// (local_source_name, local_recommendation_id) are deliberately not updatable —
// they are snapshots written by the agent.
func (q *Queries) UpdateItineraryItem(ctx context.Context, arg UpdateItineraryItemParams) (ItineraryItem, error) {
	row := q.db.QueryRow(ctx, updateItineraryItem,
		arg.Name,
		arg.PlaceID,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Category,
		arg.TimeOfDay,
		arg.City,
		arg.DayTripFrom,
		arg.Day,
		arg.ID,
		arg.TripID,
	)
	var i ItineraryItem
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Position,
		&i.Name,
		&i.PlaceID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.Category,
		&i.TimeOfDay,
		&i.City,
		&i.DayTripFrom,
		&i.Day,
		&i.LocalSourceName,
		&i.LocalRecommendationID,
	)
	return i, err
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET title      = COALESCE($1, title),
    start_date = COALESCE($2, start_date),
    end_date   = COALESCE($3, end_date),
    chat_id    = COALESCE($4, chat_id),
    travel_mode = COALESCE($5, travel_mode)
WHERE id = $6 AND user_id = $7
RETURNING id, user_id, created_at, updated_at, title, start_date, end_date, chat_id, summary, updated_by, travel_mode, origin, origin_airport, return_airport, summary_source
`

type UpdateTripParams struct {
	Title      *string     `json:"title"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	ChatID     *string     `json:"chat_id"`
	TravelMode *string     `json:"travel_mode"`
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trip, error) {
	row := q.db.QueryRow(ctx, updateTrip,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.ChatID,
		arg.TravelMode,
		arg.ID,
		arg.UserID,
	)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.ChatID,
		&i.Summary,
		&i.UpdatedBy,
		&i.TravelMode,
		&i.Origin,
		&i.OriginAirport,
		&i.ReturnAirport,
		&i.SummarySource,
	)
	return i, err
}
