// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trip_leg_gateways.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const listTripLegGateways = `-- name: ListTripLegGateways :many
SELECT trip_id, city_fold, airport, airport_label, source, created_at, updated_at FROM trip_leg_gateways WHERE trip_id = $1
`

func (q *Queries) ListTripLegGateways(ctx context.Context, tripID uuid.UUID) ([]TripLegGateway, error) {
	rows, err := q.db.Query(ctx, listTripLegGateways, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TripLegGateway
	for rows.Next() {
		var i TripLegGateway
		if err := rows.Scan(
			&i.TripID,
			&i.CityFold,
			&i.Airport,
			&i.AirportLabel,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTripLegGateway = `-- name: UpsertTripLegGateway :one
INSERT INTO trip_leg_gateways (trip_id, city_fold, airport, airport_label, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (trip_id, city_fold) DO UPDATE
SET airport = EXCLUDED.airport,
    airport_label = EXCLUDED.airport_label,
    source = EXCLUDED.source,
    updated_at = now()
WHERE trip_leg_gateways.source <> 'traveler' OR EXCLUDED.source = 'traveler'
RETURNING trip_id, city_fold, airport, airport_label, source, created_at, updated_at
`

type UpsertTripLegGatewayParams struct {
	TripID       uuid.UUID `json:"trip_id"`
	CityFold     string    `json:"city_fold"`
	Airport      string    `json:"airport"`
	AirportLabel *string   `json:"airport_label"`
	Source       string    `json:"source"`
}

// Provenance ladder in one statement: a 'traveler' row yields only to another
// 'traveler' write; 'auto' and 'self' yield to anything newer. When the WHERE
// on the conflict arm rejects the write, the statement updates nothing and
// RETURNING yields NO row — callers must treat ErrNoRows as "an earlier
// traveler decision won", never as a failure.
func (q *Queries) UpsertTripLegGateway(ctx context.Context, arg UpsertTripLegGatewayParams) (TripLegGateway, error) {
	row := q.db.QueryRow(ctx, upsertTripLegGateway,
		arg.TripID,
		arg.CityFold,
		arg.Airport,
		arg.AirportLabel,
		arg.Source,
	)
	var i TripLegGateway
	err := row.Scan(
		&i.TripID,
		&i.CityFold,
		&i.Airport,
		&i.AirportLabel,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
